port: 4869
app_env: production
admin_token: ""
ws:
    rate_limit: 1
    burst: 5
    auth: true
    auth_mode: optional
relay_information:
    url: http://192.168.1.157:4869
    name: Nostr Relay Server
    description: A Nostr Relay Server
    pub_key: "7ef721e77149c737014971b141b0b590a5ebe82b79130228cdbe56e9be2d8e50"
    priv_key: "e4d347b85fe3429ac1995d3eab801a3858990f66fb0"
    supported_nips:
        - 11 # Documento de informações do relé
        - 1 # Descrição básica do fluxo do protocolo
        - 2 # Lista de seguidores
        - 4
        - 25
        - 9
        - 23 # Long-form Content
        - 45 # Event Counts
        - 42 # Authentication of clients to relays
        - 17
        - 62 # Request to Vanish
        - 40 # Expiration Timestamp
        - 18
        - 13 # Proof of Work
    software: https://github.com/gabrielmoura/nostr-relay-server
    version: 0.1.0
    canonical_url: ws://192.168.1.157:4869
    icon: http://localhost:4869/nostr.png
relay:
    query_limit: 100
    query_ids_limit: 500
    query_authors_limit: 500
    query_kinds_limit: 500
    query_tags_limit: 400
    keep_recent_events: true
    max_size_event_in_bytes: 100000
    filter_limit: 9999999999
    reporting_limit: 5
    enable_anonymous_req: true
    max_tag_value_length: 150
    enable_empty_filter: true
db:
    max_conns: 50
    min_conns: 1
    max_conn_lifetime_minutes: 30
    max_conn_idle_minutes: 5
    health_check_period_seconds: 30
    postgres_uri: postgres://postgres:Strong@P4ssword@127.0.0.1:5432/nostr
redis:
  enabled: true
  addr: "127.0.0.1:6379"
  pool_size: 10
  subscription_cleanup_interval_seconds: 60
  subscription_stale_after_seconds: 120
  cache:
    ban_ttl: 3600
    profile_ttl: 300
    query_ttl: 30
    query_meta_ttl: 30
    event_ttl: 600
    dedup_ttl: 3600

stream:
    relays:
        - wss://cobrafuma.com/relay
        - wss://nexus.libernet.app
    stream_down: false
    stream_up: true
cron:
    enabled: false
    db_optimization:
        enabled: false
        schedule: "0 30 3 * * *"
        analyze: true
        vacuum_analyze: false
        reindex_event: false
    reported_events_fetch:
        enabled: false
        schedule: "0 */30 * * * *"
        relays: []
        lookback_hours: 24
        limit_per_relay: 200
    delete_old_events:
        enabled: false
        schedule: "0 0 4 * * *"
        older_than_days: 365
        batch_size: 2000
store:
    enabled: true
    api_path: http://localhost:4869/upload
    media_path: http://localhost:4869/blob
    accepted_mimetypes:
        - image/jpeg
        - image/png
        - image/gif
        - image/webp
        - image/svg+xml
        - video/mp4
        - video/webm
        - video/ogg
        - audio/mpeg
        - audio/ogg
        - audio/wav
        - audio/flac
        - audio/aac
        - audio/mp4
        - audio/opus
        - audio/vorbis
    allow_adult_content: false
    allow_violent_content: false
    names: [ ]
