{
 "title": "Nostr Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Request", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request by Kind",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "{job=\"nostr\", __name__=\"nostr_kind_request_count\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "{job=\"nostr\", __name__=\"nostr_request_count\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Blossom", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Nostr Upload",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{job=\"nostr\", __name__=\"nostr_uploads\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nostr Download",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "{job=\"nostr\", __name__=\"nostr_downloads\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}