@base_url = 192.168.1.103:9090
### Connect ao Relay
WEBSOCKET ws://{{base_url}}/relay
Content-Type: application/json

### Boas vindas do Relay
GET http://{{base_url}}

### Buscar o informações do Relay
GET http://{{base_url}}/relay
Accept: application/nostr+json