package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
	"github.com/gabrielmoura/nostr-relay-server/graph/model"
)

// DisconnectConnection is the resolver for the disconnectConnection field.
func (r *mutationResolver) DisconnectConnection(ctx context.Context, wsid string, reason *string) (*model.MutationAck, error) {
	return r.disconnectConnection(ctx, wsid, reason)
}

// BanUser is the resolver for the banUser field.
func (r *mutationResolver) BanUser(ctx context.Context, pubkey string, input model.AdminBanUserInput) (*model.AdminBanStatus, error) {
	return r.banUser(ctx, pubkey, input)
}

// UnbanUser is the resolver for the unbanUser field.
func (r *mutationResolver) UnbanUser(ctx context.Context, pubkey string) (*model.AdminBanStatus, error) {
	return r.unbanUser(ctx, pubkey)
}

// UpsertNip05 is the resolver for the upsertNip05 field.
func (r *mutationResolver) UpsertNip05(ctx context.Context, input model.AdminNip05UpsertInput) (*model.AdminNip05Identity, error) {
	return r.upsertNip05(ctx, input)
}

// DeleteNip05 is the resolver for the deleteNip05 field.
func (r *mutationResolver) DeleteNip05(ctx context.Context, name string) (*model.MutationAck, error) {
	return r.deleteNip05(ctx, name)
}

// ImportEvents is the resolver for the importEvents field.
func (r *mutationResolver) ImportEvents(ctx context.Context, files []*graphql.Upload) (*model.AdminImportEventsPayload, error) {
	return r.importEvents(ctx, files)
}

// FetchEventFromRelays is the resolver for the fetchEventFromRelays field.
func (r *mutationResolver) FetchEventFromRelays(ctx context.Context, id string, input *model.AdminFetchEventInput) (*model.AdminFetchEventPayload, error) {
	return r.fetchEventFromRelays(ctx, id, input)
}

// CreateLabel is the resolver for the createLabel field.
func (r *mutationResolver) CreateLabel(ctx context.Context, input model.AdminCreateLabelInput) (*model.AdminCreateLabelPayload, error) {
	return r.createLabel(ctx, input)
}

// UpsertBlossomPolicy is the resolver for the upsertBlossomPolicy field.
func (r *mutationResolver) UpsertBlossomPolicy(ctx context.Context, input model.AdminBlossomPolicyInput) (*model.AdminBlossomPolicy, error) {
	return r.upsertBlossomPolicy(ctx, input)
}

// UpsertBlossomPlan is the resolver for the upsertBlossomPlan field.
func (r *mutationResolver) UpsertBlossomPlan(ctx context.Context, input model.AdminBlossomPlanInput) (*model.AdminBlossomPlan, error) {
	return r.upsertBlossomPlan(ctx, input)
}

// DeleteBlossomPlan is the resolver for the deleteBlossomPlan field.
func (r *mutationResolver) DeleteBlossomPlan(ctx context.Context, id string) (*model.MutationAck, error) {
	return r.deleteBlossomPlan(ctx, id)
}

// AssignBlossomPlan is the resolver for the assignBlossomPlan field.
func (r *mutationResolver) AssignBlossomPlan(ctx context.Context, planID string, pubkey string) (*model.MutationAck, error) {
	return r.assignBlossomPlan(ctx, planID, pubkey)
}

// UnassignBlossomPlan is the resolver for the unassignBlossomPlan field.
func (r *mutationResolver) UnassignBlossomPlan(ctx context.Context, planID string, pubkey string) (*model.MutationAck, error) {
	return r.unassignBlossomPlan(ctx, planID, pubkey)
}

// ReviewBlossomObjects is the resolver for the reviewBlossomObjects field.
func (r *mutationResolver) ReviewBlossomObjects(ctx context.Context, input model.AdminBlossomBulkReviewInput) (*model.MutationAck, error) {
	return r.reviewBlossomObjects(ctx, input)
}

// UpsertBlossomWhitelist is the resolver for the upsertBlossomWhitelist field.
func (r *mutationResolver) UpsertBlossomWhitelist(ctx context.Context, input model.AdminBlossomWhitelistInput) (*model.AdminBlossomUser, error) {
	return r.upsertBlossomWhitelist(ctx, input)
}

// PurgeBlossomUser is the resolver for the purgeBlossomUser field.
func (r *mutationResolver) PurgeBlossomUser(ctx context.Context, pubkey string) (*model.MutationAck, error) {
	return r.purgeBlossomUser(ctx, pubkey)
}

// MirrorBlossomObject is the resolver for the mirrorBlossomObject field.
func (r *mutationResolver) MirrorBlossomObject(ctx context.Context, input model.AdminBlossomMirrorInput) (*model.AdminAsyncJob, error) {
	return r.mirrorBlossomObject(ctx, input)
}

// ResolveBlossomReport is the resolver for the resolveBlossomReport field.
func (r *mutationResolver) ResolveBlossomReport(ctx context.Context, id string, input model.AdminBlossomResolveReportInput) (*model.AdminBlossomReport, error) {
	return r.resolveBlossomReport(ctx, id, input)
}

// CreateNip86AllowedPubkey is the resolver for the createNip86AllowedPubkey field.
func (r *mutationResolver) CreateNip86AllowedPubkey(ctx context.Context, pubkey string, input *model.AdminNip86ReasonInput) (*model.MutationAck, error) {
	return r.createNip86AllowedPubkey(ctx, pubkey, input)
}

// DeleteNip86AllowedPubkey is the resolver for the deleteNip86AllowedPubkey field.
func (r *mutationResolver) DeleteNip86AllowedPubkey(ctx context.Context, pubkey string) (*model.MutationAck, error) {
	return r.deleteNip86AllowedPubkey(ctx, pubkey)
}

// CreateNip86BlockedIP is the resolver for the createNip86BlockedIp field.
func (r *mutationResolver) CreateNip86BlockedIP(ctx context.Context, ip string, input *model.AdminNip86ReasonInput) (*model.MutationAck, error) {
	return r.createNip86BlockedIP(ctx, ip, input)
}

// DeleteNip86BlockedIP is the resolver for the deleteNip86BlockedIp field.
func (r *mutationResolver) DeleteNip86BlockedIP(ctx context.Context, ip string) (*model.MutationAck, error) {
	return r.deleteNip86BlockedIP(ctx, ip)
}

// CreateNip86BannedEvent is the resolver for the createNip86BannedEvent field.
func (r *mutationResolver) CreateNip86BannedEvent(ctx context.Context, eventID string, input *model.AdminNip86ReasonInput) (*model.MutationAck, error) {
	return r.createNip86BannedEvent(ctx, eventID, input)
}

// DeleteNip86BannedEvent is the resolver for the deleteNip86BannedEvent field.
func (r *mutationResolver) DeleteNip86BannedEvent(ctx context.Context, eventID string) (*model.MutationAck, error) {
	return r.deleteNip86BannedEvent(ctx, eventID)
}

// UpdateNip86RelayMetadata is the resolver for the updateNip86RelayMetadata field.
func (r *mutationResolver) UpdateNip86RelayMetadata(ctx context.Context, input model.AdminNip86RelayMetadataInput) (*model.AdminNip86RelayMetadata, error) {
	return r.updateNip86RelayMetadata(ctx, input)
}

// StartNegentropySync is the resolver for the startNegentropySync field.
func (r *mutationResolver) StartNegentropySync(ctx context.Context, input model.AdminNegentropySyncInput) (*model.AdminAsyncJob, error) {
	return r.startNegentropySync(ctx, input)
}

// DownloadEvents is the resolver for the downloadEvents field.
func (r *mutationResolver) DownloadEvents(ctx context.Context, input model.AdminDownloadEventsInput) (*model.AdminAsyncJob, error) {
	return r.downloadEvents(ctx, input)
}

// RetryJob is the resolver for the retryJob field.
func (r *mutationResolver) RetryJob(ctx context.Context, id string, queue *string) (*model.MutationAck, error) {
	return r.retryJob(ctx, id, queue)
}

// CancelJob is the resolver for the cancelJob field.
func (r *mutationResolver) CancelJob(ctx context.Context, id string, queue *string) (*model.MutationAck, error) {
	return r.cancelJob(ctx, id, queue)
}

// ResumeJob is the resolver for the resumeJob field.
func (r *mutationResolver) ResumeJob(ctx context.Context, id string, queue *string) (*model.MutationAck, error) {
	return r.resumeJob(ctx, id, queue)
}

// DeleteJobsHistory is the resolver for the deleteJobsHistory field.
func (r *mutationResolver) DeleteJobsHistory(ctx context.Context, input model.AdminDeleteJobsHistoryInput) (*model.MutationAck, error) {
	return r.deleteJobsHistory(ctx, input)
}

// AddTrustedPubkey is the resolver for the addTrustedPubkey field.
func (r *mutationResolver) AddTrustedPubkey(ctx context.Context, pubkey string) (*model.AdminWoTSummary, error) {
	return r.addTrustedPubkey(ctx, pubkey)
}

// RemoveTrustedPubkey is the resolver for the removeTrustedPubkey field.
func (r *mutationResolver) RemoveTrustedPubkey(ctx context.Context, pubkey string) (*model.AdminWoTSummary, error) {
	return r.removeTrustedPubkey(ctx, pubkey)
}

// AdminOverview is the resolver for the adminOverview field.
func (r *queryResolver) AdminOverview(ctx context.Context) (*model.AdminOverview, error) {
	return r.adminOverview(ctx)
}

// AdminStreamStatus is the resolver for the adminStreamStatus field.
func (r *queryResolver) AdminStreamStatus(ctx context.Context) (*model.AdminStreamStatus, error) {
	return r.adminStreamStatus(ctx)
}

// PrivacyStatus is the resolver for the privacyStatus field.
func (r *queryResolver) PrivacyStatus(ctx context.Context) (*model.PrivacyStatus, error) {
	return r.privacyStatus(ctx)
}

// ActiveConnections is the resolver for the activeConnections field.
func (r *queryResolver) ActiveConnections(ctx context.Context, page *model.OffsetPageInput) (*model.AdminConnectionPage, error) {
	return r.activeConnections(ctx, page)
}

// AuthedConnections is the resolver for the authedConnections field.
func (r *queryResolver) AuthedConnections(ctx context.Context, page *model.OffsetPageInput) (*model.AdminConnectionPage, error) {
	return r.authedConnections(ctx, page)
}

// LoggedUsers is the resolver for the loggedUsers field.
func (r *queryResolver) LoggedUsers(ctx context.Context, page *model.OffsetPageInput) (*model.AdminLoggedUserPage, error) {
	return r.loggedUsers(ctx, page)
}

// BannedUsers is the resolver for the bannedUsers field.
func (r *queryResolver) BannedUsers(ctx context.Context, q *string, page *model.OffsetPageInput) (*model.AdminProfilePage, error) {
	return r.bannedUsers(ctx, q, page)
}

// SearchUsers is the resolver for the searchUsers field.
func (r *queryResolver) SearchUsers(ctx context.Context, q *string, page *model.OffsetPageInput) (*model.AdminProfilePage, error) {
	return r.searchUsers(ctx, q, page)
}

// UserProfile is the resolver for the userProfile field.
func (r *queryResolver) UserProfile(ctx context.Context, pubkey string) (*model.AdminProfile, error) {
	return r.userProfile(ctx, pubkey)
}

// UserBanStatus is the resolver for the userBanStatus field.
func (r *queryResolver) UserBanStatus(ctx context.Context, pubkey string) (*model.AdminBanStatus, error) {
	return r.userBanStatus(ctx, pubkey)
}

// UserNip05 is the resolver for the userNip05 field.
func (r *queryResolver) UserNip05(ctx context.Context, pubkey string) (*model.AdminNip05Lookup, error) {
	return r.userNip05(ctx, pubkey)
}

// Nip05Identities is the resolver for the nip05Identities field.
func (r *queryResolver) Nip05Identities(ctx context.Context, q *string, page *model.OffsetPageInput) (*model.AdminNip05IdentityPage, error) {
	return r.nip05Identities(ctx, q, page)
}

// Events is the resolver for the events field.
func (r *queryResolver) Events(ctx context.Context, filter *model.AdminEventSearchInput, page *model.OffsetPageInput) (*model.AdminEventPage, error) {
	return r.events(ctx, filter, page)
}

// EventAggregates is the resolver for the eventAggregates field.
func (r *queryResolver) EventAggregates(ctx context.Context, filter *model.AdminEventSearchInput) (*model.AdminEventAggregates, error) {
	return r.eventAggregates(ctx, filter)
}

// EventTimeline is the resolver for the eventTimeline field.
func (r *queryResolver) EventTimeline(ctx context.Context, filter *model.AdminEventSearchInput, bucket *model.TimelineBucket) (*model.AdminTimeline, error) {
	return r.eventTimeline(ctx, filter, bucket)
}

// EventDetail is the resolver for the eventDetail field.
func (r *queryResolver) EventDetail(ctx context.Context, id string) (*model.AdminEventDetail, error) {
	return r.eventDetail(ctx, id)
}

// EventReports is the resolver for the eventReports field.
func (r *queryResolver) EventReports(ctx context.Context, id string, page *model.OffsetPageInput) (*model.AdminEventReportPage, error) {
	return r.eventReports(ctx, id, page)
}

// ReportedEvents is the resolver for the reportedEvents field.
func (r *queryResolver) ReportedEvents(ctx context.Context, filter *model.AdminReportedEventFilterInput, page *model.OffsetPageInput) (*model.AdminReportedEventPage, error) {
	return r.reportedEvents(ctx, filter, page)
}

// ReportedEventsSummary is the resolver for the reportedEventsSummary field.
func (r *queryResolver) ReportedEventsSummary(ctx context.Context, filter *model.AdminReportedEventFilterInput) (*model.AdminReportedEventsSummary, error) {
	return r.reportedEventsSummary(ctx, filter)
}

// Labels is the resolver for the labels field.
func (r *queryResolver) Labels(ctx context.Context, filter *model.AdminLabelFilterInput, page *model.OffsetPageInput) (*model.AdminLabelPage, error) {
	return r.labels(ctx, filter, page)
}

// LabelsSummary is the resolver for the labelsSummary field.
func (r *queryResolver) LabelsSummary(ctx context.Context, filter *model.AdminLabelFilterInput) (*model.AdminLabelsSummary, error) {
	return r.labelsSummary(ctx, filter)
}

// BlossomOverview is the resolver for the blossomOverview field.
func (r *queryResolver) BlossomOverview(ctx context.Context) (*model.AdminBlossomOverview, error) {
	return r.blossomOverview(ctx)
}

// BlossomPolicy is the resolver for the blossomPolicy field.
func (r *queryResolver) BlossomPolicy(ctx context.Context) (*model.AdminBlossomPolicy, error) {
	return r.blossomPolicy(ctx)
}

// BlossomPlans is the resolver for the blossomPlans field.
func (r *queryResolver) BlossomPlans(ctx context.Context) ([]*model.AdminBlossomPlan, error) {
	return r.blossomPlans(ctx)
}

// BlossomPlanAssignments is the resolver for the blossomPlanAssignments field.
func (r *queryResolver) BlossomPlanAssignments(ctx context.Context, planID string, page *model.OffsetPageInput) (*model.AdminBlossomPlanAssignmentPage, error) {
	return r.blossomPlanAssignments(ctx, planID, page)
}

// BlossomObjects is the resolver for the blossomObjects field.
func (r *queryResolver) BlossomObjects(ctx context.Context, filter *model.AdminBlossomObjectFilterInput, page *model.OffsetPageInput) (*model.AdminBlossomObjectPage, error) {
	return r.blossomObjects(ctx, filter, page)
}

// BlossomObject is the resolver for the blossomObject field.
func (r *queryResolver) BlossomObject(ctx context.Context, hash string) (*model.AdminBlossomObject, error) {
	return r.blossomObject(ctx, hash)
}

// BlossomUsers is the resolver for the blossomUsers field.
func (r *queryResolver) BlossomUsers(ctx context.Context, filter *model.AdminBlossomUserFilterInput, page *model.OffsetPageInput) (*model.AdminBlossomUserPage, error) {
	return r.blossomUsers(ctx, filter, page)
}

// BlossomUser is the resolver for the blossomUser field.
func (r *queryResolver) BlossomUser(ctx context.Context, pubkey string) (*model.AdminBlossomUserDetail, error) {
	return r.blossomUser(ctx, pubkey)
}

// BlossomReports is the resolver for the blossomReports field.
func (r *queryResolver) BlossomReports(ctx context.Context, filter *model.AdminBlossomReportFilterInput, page *model.OffsetPageInput) (*model.AdminBlossomReportPage, error) {
	return r.blossomReports(ctx, filter, page)
}

// BlossomAnalytics is the resolver for the blossomAnalytics field.
func (r *queryResolver) BlossomAnalytics(ctx context.Context) (map[string]any, error) {
	return r.blossomAnalytics(ctx)
}

// BlossomWorkers is the resolver for the blossomWorkers field.
func (r *queryResolver) BlossomWorkers(ctx context.Context, status *string, jobType *string, targetHash *string, page *model.OffsetPageInput) (*model.AdminBlossomWorkerPage, error) {
	return r.blossomWorkers(ctx, status, jobType, targetHash, page)
}

// BlossomAudit is the resolver for the blossomAudit field.
func (r *queryResolver) BlossomAudit(ctx context.Context, page *model.OffsetPageInput) (*model.AdminBlossomAuditPage, error) {
	return r.blossomAudit(ctx, page)
}

// Nip86AllowedPubkeys is the resolver for the nip86AllowedPubkeys field.
func (r *queryResolver) Nip86AllowedPubkeys(ctx context.Context, q *string, page *model.OffsetPageInput) (*model.AdminNip86PubkeyPage, error) {
	return r.nip86AllowedPubkeys(ctx, q, page)
}

// Nip86BlockedIps is the resolver for the nip86BlockedIps field.
func (r *queryResolver) Nip86BlockedIps(ctx context.Context, q *string, page *model.OffsetPageInput) (*model.AdminNip86IPPage, error) {
	return r.nip86BlockedIps(ctx, q, page)
}

// Nip86BannedEvents is the resolver for the nip86BannedEvents field.
func (r *queryResolver) Nip86BannedEvents(ctx context.Context, q *string, page *model.OffsetPageInput) (*model.AdminNip86EventPage, error) {
	return r.nip86BannedEvents(ctx, q, page)
}

// Nip86RelayMetadata is the resolver for the nip86RelayMetadata field.
func (r *queryResolver) Nip86RelayMetadata(ctx context.Context) (*model.AdminNip86RelayMetadata, error) {
	return r.nip86RelayMetadata(ctx)
}

// Jobs is the resolver for the jobs field.
func (r *queryResolver) Jobs(ctx context.Context, filter *model.AdminJobFilterInput, page *model.OffsetPageInput) (*model.AdminJobPage, error) {
	return r.jobs(ctx, filter, page)
}

// Job is the resolver for the job field.
func (r *queryResolver) Job(ctx context.Context, id string, queue *string) (*model.AdminJob, error) {
	return r.job(ctx, id, queue)
}

// Groups is the resolver for the groups field.
func (r *queryResolver) Groups(ctx context.Context) ([]*model.AdminGroup, error) {
	return r.groups(ctx)
}

// WotSummary is the resolver for the wotSummary field.
func (r *queryResolver) WotSummary(ctx context.Context) (*model.AdminWoTSummary, error) {
	return r.wotSummary(ctx)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
