-- ============================================================
-- PostgreSQL 18 optimized schema — v2 (refatorado)
-- ============================================================
-- Decisões tomadas nesta revisão:
--   1) Prefixo hex (ex.: id LIKE 'abc%') É usado pelo relay -> mantido
--      o índice UNIQUE text_pattern_ops em event.id.
--   2) Adicionado índice GIN em tagvalues (estava órfão: coluna gerada
--      sem índice de suporte).
--   3) Limpeza de eventos expirados é feita por um CRON externo ->
--      não foi adicionada coluna/índice de expires_at aqui.
--   4) Particionamento por data é PLANO FUTURO: a estratégia definida
--      é mover eventos antigos (ex.: > 5 anos) para uma tabela de
--      arquivamento separada, não particionamento nativo. Por isso
--      o índice parcial com epoch hardcoded (idx_event_recent) foi
--      removido — ele é um paliativo que a estratégia de arquivamento
--      torna desnecessário e que exigiria manutenção manual constante.
--   5) Não há limite de quantidade de tags no banco (chegam a existir
--      eventos com ~2000 tags). Por isso os índices sobre `tags` e
--      `tagvalues` usam GIN (não sofre do limite de ~2712 bytes por
--      tupla de índice btree que afeta índices "covering"). A
--      restrição de tamanho de payload, se necessária, fica na
--      camada de aplicação.
-- ============================================================

CREATE SCHEMA IF NOT EXISTS public;

-- ============================================================
-- Functions
-- ============================================================

CREATE OR REPLACE FUNCTION public.tags_to_tagvalues(input jsonb)
    RETURNS text[]
    LANGUAGE sql
    IMMUTABLE
    STRICT
AS $$
SELECT array_agg(t->>1)
FROM (
         SELECT jsonb_array_elements(input) AS t
     ) s
WHERE length(t->>0) = 1;
$$;

-- Validação de expiração otimizada: evita o custo de subtransação de
-- uma EXCEPTION em um trigger que roda em todo INSERT. A limpeza dos
-- eventos já expirados e persistidos continua a cargo do cron externo.
CREATE OR REPLACE FUNCTION public.nostr_expiration_submission()
    RETURNS trigger
    LANGUAGE plpgsql
    VOLATILE
AS $$
DECLARE
    expiration_tag       jsonb;
    expiration_value     text;
    expiration_timestamp integer;
    unix_now             integer;
BEGIN
    SELECT value
    INTO expiration_tag
    FROM jsonb_array_elements(NEW.tags) AS value
    WHERE value ->> 0 = 'expiration'
    LIMIT 1;

    IF expiration_tag IS NULL THEN
        RETURN NEW;
    END IF;

    expiration_value := expiration_tag ->> 1;

    IF expiration_value !~ '^\d+$' THEN
        RAISE EXCEPTION 'Invalid expiration timestamp: %', expiration_value;
    END IF;

    expiration_timestamp := expiration_value::integer;
    unix_now := extract(epoch FROM now())::integer;

    IF expiration_timestamp < unix_now THEN
        RAISE EXCEPTION 'expired event';
    END IF;

    RETURN NEW;
END;
$$;

-- ============================================================
-- Core tables
-- ============================================================

CREATE TABLE IF NOT EXISTS public.profiles (
                                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                               public_key VARCHAR(64) NOT NULL UNIQUE CHECK (length(public_key) = 64),
                                               name TEXT NOT NULL,
                                               about TEXT,
                                               picture TEXT,
                                               bot BOOLEAN DEFAULT FALSE,
                                               banner TEXT,
                                               website TEXT,
                                               display_name TEXT,
                                               lud16 TEXT,
                                               pronouns TEXT,
                                               nip05 TEXT,
                                               enable_nip05 BOOLEAN DEFAULT FALSE,
                                               enable_store_files BOOLEAN DEFAULT FALSE
);

-- Sem limite de tamanho/quantidade de tags no schema (ver nota 5 no topo).
CREATE TABLE IF NOT EXISTS public.event (
                                            id TEXT PRIMARY KEY,
                                            pubkey TEXT NOT NULL,
                                            created_at INTEGER NOT NULL,
                                            kind INTEGER NOT NULL,
                                            tags JSONB NOT NULL,
                                            content TEXT NOT NULL,
                                            sig TEXT NOT NULL,
                                            tagvalues TEXT[] GENERATED ALWAYS AS (public.tags_to_tagvalues(tags)) STORED,
                                            content_search TSVECTOR GENERATED ALWAYS AS (
                                                to_tsvector('simple'::regconfig, content)
                                                ) STORED,
                                            deleted_by VARCHAR(64)
);

-- Constraints de integridade adicionadas de forma idempotente
-- (mesmo padrão de DO block já usado no arquivo original para o trigger).
DO $$
    BEGIN
        IF NOT EXISTS (
            SELECT 1 FROM pg_constraint WHERE conname = 'chk_event_pubkey_length'
        ) THEN
            ALTER TABLE public.event
                ADD CONSTRAINT chk_event_pubkey_length CHECK (length(pubkey) = 64);
        END IF;

        IF NOT EXISTS (
            SELECT 1 FROM pg_constraint WHERE conname = 'chk_event_sig_length'
        ) THEN
            ALTER TABLE public.event
                ADD CONSTRAINT chk_event_sig_length CHECK (length(sig) = 128);
        END IF;
    END $$;

CREATE TABLE IF NOT EXISTS public.nip05 (
                                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                            pubkey TEXT NOT NULL,
                                            name VARCHAR(32) NOT NULL,
                                            expire_at TIMESTAMPTZ,
                                            enabled BOOLEAN DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS public.nip05_identities (
                                                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                       name TEXT NOT NULL UNIQUE,
                                                       public_key VARCHAR(64) NOT NULL UNIQUE REFERENCES public.profiles(public_key) ON DELETE CASCADE,
                                                       created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                                                       updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.banned_users (
                                                   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                   user_id BIGINT NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
                                                   reason TEXT NOT NULL,
                                                   related_ids VARCHAR(60)[],
                                                   created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================
-- Blossom / objects
-- ============================================================

CREATE TABLE IF NOT EXISTS public.objects (
                                              hash VARCHAR(200) PRIMARY KEY,
                                              created_at TIMESTAMPTZ NOT NULL,
                                              mime_type VARCHAR(255),
                                              size BIGINT,
                                              blocked BOOLEAN,
                                              expires_at TIMESTAMPTZ,
                                              blocked_by_reason TEXT,
                                              public_key VARCHAR(64),
                                              tags JSONB
);

CREATE TABLE IF NOT EXISTS public.blossom_objects_admin (
                                                            hash VARCHAR(200) PRIMARY KEY REFERENCES public.objects(hash) ON DELETE CASCADE,
                                                            extension VARCHAR(32) NOT NULL DEFAULT '',
                                                            width INTEGER,
                                                            height INTEGER,
                                                            duration_ms BIGINT,
                                                            bitrate_kbps INTEGER,
                                                            blurhash TEXT,
                                                            thumbnail_hash VARCHAR(64),
                                                            optimized_hash VARCHAR(64),
                                                            hls_manifest_hash VARCHAR(64),
                                                            processing_status VARCHAR(24) NOT NULL DEFAULT 'pending',
                                                            processing_error TEXT,
                                                            exif_status VARCHAR(24) NOT NULL DEFAULT 'pending',
                                                            gps_detected BOOLEAN NOT NULL DEFAULT FALSE,
                                                            last_downloaded_at TIMESTAMPTZ,
                                                            download_count BIGINT NOT NULL DEFAULT 0,
                                                            ingress_bytes BIGINT NOT NULL DEFAULT 0,
                                                            egress_bytes BIGINT NOT NULL DEFAULT 0,
                                                            review_state VARCHAR(24) NOT NULL DEFAULT 'ready',
                                                            flag_reason TEXT,
                                                            nip94_tags JSONB NOT NULL DEFAULT '[]'::jsonb,
                                                            mirrors JSONB NOT NULL DEFAULT '[]'::jsonb,
                                                            updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.blossom_pubkey_quotas (
                                                            pubkey VARCHAR(64) PRIMARY KEY,
                                                            enabled BOOLEAN NOT NULL DEFAULT TRUE,
                                                            storage_quota_bytes BIGINT,
                                                            egress_quota_bytes BIGINT,
                                                            notes TEXT,
                                                            created_by VARCHAR(64) NOT NULL,
                                                            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                                                            updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.blossom_server_policy (
                                                            id SMALLINT PRIMARY KEY,
                                                            mode VARCHAR(24) NOT NULL,
                                                            default_storage_quota_bytes BIGINT,
                                                            default_egress_quota_bytes BIGINT,
                                                            enabled_user_default_storage_quota_bytes BIGINT,
                                                            enabled_user_default_egress_quota_bytes BIGINT,
                                                            updated_by VARCHAR(64) NOT NULL,
                                                            updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.blossom_plans (
                                                    id VARCHAR(64) PRIMARY KEY,
                                                    name VARCHAR(120) NOT NULL,
                                                    scope VARCHAR(24) NOT NULL,
                                                    storage_quota_bytes BIGINT,
                                                    egress_quota_bytes BIGINT,
                                                    description TEXT,
                                                    is_default BOOLEAN NOT NULL DEFAULT FALSE,
                                                    updated_by VARCHAR(64) NOT NULL,
                                                    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.blossom_plan_assignments (
                                                               pubkey VARCHAR(64) PRIMARY KEY,
                                                               plan_id VARCHAR(64) NOT NULL REFERENCES public.blossom_plans(id) ON DELETE CASCADE,
                                                               assigned_by VARCHAR(64) NOT NULL,
                                                               assigned_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.blossom_review_reports (
                                                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                             event_id VARCHAR(64) NOT NULL,
                                                             object_hash VARCHAR(200) NOT NULL REFERENCES public.objects(hash) ON DELETE CASCADE,
                                                             reporter_pubkey VARCHAR(64) NOT NULL,
                                                             target_event_id VARCHAR(64),
                                                             target_pubkey VARCHAR(64),
                                                             report_type VARCHAR(64),
                                                             reason TEXT,
                                                             status VARCHAR(24) NOT NULL DEFAULT 'open',
                                                             resolved_by VARCHAR(64),
                                                             resolved_note TEXT,
                                                             created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                                                             resolved_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS public.blossom_audit_log (
                                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                        actor_pubkey VARCHAR(64) NOT NULL,
                                                        action VARCHAR(64) NOT NULL,
                                                        target_type VARCHAR(32) NOT NULL,
                                                        target_id TEXT NOT NULL,
                                                        request_id TEXT,
                                                        payload JSONB NOT NULL DEFAULT '{}'::jsonb,
                                                        nostr_event_id VARCHAR(64),
                                                        created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================
-- NIP-29
-- ============================================================

CREATE TABLE IF NOT EXISTS public.nip29_roles (
                                                  role_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                  name VARCHAR(250) NOT NULL,
                                                  description TEXT
);

CREATE TABLE IF NOT EXISTS public.nip29_groups (
                                                   relay TEXT NOT NULL,
                                                   group_id TEXT NOT NULL,
                                                   name VARCHAR(255) NOT NULL,
                                                   picture TEXT,
                                                   about TEXT,
                                                   private BOOLEAN NOT NULL DEFAULT FALSE,
                                                   closed BOOLEAN NOT NULL DEFAULT FALSE,
                                                   last_metadata_update TIMESTAMPTZ NOT NULL,
                                                   last_admins_update TIMESTAMPTZ NOT NULL,
                                                   last_members_update TIMESTAMPTZ NOT NULL,
                                                   last_roles_update TIMESTAMPTZ NOT NULL,
                                                   restricted BOOLEAN NOT NULL DEFAULT FALSE,
                                                   hidden BOOLEAN NOT NULL DEFAULT FALSE,
                                                   created_by VARCHAR(64),
                                                   updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                                                   deleted_at TIMESTAMPTZ,
                                                   min_pow INTEGER NOT NULL DEFAULT 0,
                                                   require_moderation_timeline_ref BOOLEAN NOT NULL DEFAULT FALSE,
                                                   min_timeline_references INTEGER NOT NULL DEFAULT 0,
                                                   timeline_recent_window INTEGER NOT NULL DEFAULT 50,
                                                   allow_late_publication BOOLEAN NOT NULL DEFAULT FALSE,
                                                   PRIMARY KEY (relay, group_id)
);

CREATE TABLE IF NOT EXISTS public.nip29_group_roles (
                                                        relay TEXT NOT NULL,
                                                        group_id TEXT NOT NULL,
                                                        role_id INTEGER NOT NULL REFERENCES public.nip29_roles(role_id) ON DELETE CASCADE,
                                                        PRIMARY KEY (relay, group_id, role_id),
                                                        FOREIGN KEY (relay, group_id) REFERENCES public.nip29_groups(relay, group_id) ON DELETE CASCADE
);

-- 'banned' removido da PK: um mesmo (relay, group_id, user_id, role_id)
-- não pode existir em dois estados de banimento simultâneos, o que a
-- versão anterior permitia por engano.
CREATE TABLE IF NOT EXISTS public.nip29_group_members (
                                                          relay TEXT NOT NULL,
                                                          group_id TEXT NOT NULL,
                                                          user_id VARCHAR(64) NOT NULL,
                                                          role_id INTEGER NOT NULL REFERENCES public.nip29_roles(role_id) ON DELETE CASCADE,
                                                          banned BOOLEAN NOT NULL DEFAULT FALSE,
                                                          PRIMARY KEY (relay, group_id, user_id, role_id),
                                                          FOREIGN KEY (relay, group_id) REFERENCES public.nip29_groups(relay, group_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.nip29_group_bans (
                                                       relay TEXT NOT NULL,
                                                       group_id TEXT NOT NULL,
                                                       user_id VARCHAR(64) NOT NULL,
                                                       reason TEXT,
                                                       created_by VARCHAR(64),
                                                       created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                                                       PRIMARY KEY (relay, group_id, user_id),
                                                       FOREIGN KEY (relay, group_id) REFERENCES public.nip29_groups(relay, group_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.nip29_group_invites (
                                                          relay TEXT NOT NULL,
                                                          group_id TEXT NOT NULL,
                                                          code TEXT NOT NULL,
                                                          created_by VARCHAR(64) NOT NULL,
                                                          max_uses INTEGER NOT NULL DEFAULT 1,
                                                          uses INTEGER NOT NULL DEFAULT 0,
                                                          expires_at TIMESTAMPTZ,
                                                          revoked_at TIMESTAMPTZ,
                                                          created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                                                          last_used_at TIMESTAMPTZ,
                                                          PRIMARY KEY (relay, group_id, code),
                                                          FOREIGN KEY (relay, group_id) REFERENCES public.nip29_groups(relay, group_id) ON DELETE CASCADE
);

-- ============================================================
-- NIP-86
-- ============================================================

CREATE TABLE IF NOT EXISTS public.nip86_allowed_pubkeys (
                                                            pubkey VARCHAR(64) PRIMARY KEY,
                                                            reason TEXT,
                                                            created_by VARCHAR(64) NOT NULL,
                                                            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                                                            updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.nip86_banned_events (
                                                          event_id VARCHAR(64) PRIMARY KEY,
                                                          reason TEXT,
                                                          created_by VARCHAR(64) NOT NULL,
                                                          created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                                                          updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.nip86_blocked_ips (
                                                        ip INET PRIMARY KEY,
                                                        reason TEXT,
                                                        created_by VARCHAR(64) NOT NULL,
                                                        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                                                        updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.nip86_relay_metadata (
                                                           relay_url TEXT PRIMARY KEY,
                                                           name TEXT,
                                                           description TEXT,
                                                           updated_by VARCHAR(64) NOT NULL,
                                                           updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================
-- Trigger idempotente para expiration
-- ============================================================

DO $$
    BEGIN
        IF NOT EXISTS (
            SELECT 1
            FROM pg_trigger
            WHERE tgname = 'trg_event_expiration'
        ) THEN
            CREATE TRIGGER trg_event_expiration
                BEFORE INSERT ON public.event
                FOR EACH ROW
            EXECUTE FUNCTION public.nostr_expiration_submission();
        END IF;
    END $$;

-- ============================================================
-- Índices normais
-- ============================================================

-- Mantido: usado para busca por prefixo hex (id LIKE 'abc%').
CREATE UNIQUE INDEX IF NOT EXISTS ididx
    ON public.event USING btree (id text_pattern_ops);

CREATE INDEX IF NOT EXISTS pubkeyprefix
    ON public.event USING btree (pubkey text_pattern_ops);

-- Substitui timeidx + idx_event_created_at_id: um único índice composto
-- serve tanto "ORDER BY created_at DESC" quanto paginação por cursor
-- (WHERE created_at <= :cursor ORDER BY created_at DESC, id DESC).
CREATE INDEX IF NOT EXISTS idx_event_created_at_id
    ON public.event (created_at DESC, id DESC);

-- kindidx removido: redundante com kindtimeidx (kind, created_at DESC),
-- que já cobre filtros só por "kind" via regra do prefixo esquerdo do btree.
CREATE INDEX IF NOT EXISTS kindtimeidx
    ON public.event (kind, created_at DESC);

CREATE INDEX IF NOT EXISTS content_search_idx
    ON public.event USING gin (content_search);

CREATE INDEX IF NOT EXISTS pubkey_nip05_name
    ON public.nip05 (pubkey, name);

-- Garante unicidade lógica: um nome NIP-05 habilitado não pode apontar
-- para mais de uma pubkey simultaneamente. Nomes desabilitados podem
-- ser reaproveitados no histórico.
CREATE UNIQUE INDEX IF NOT EXISTS uq_nip05_name_enabled
    ON public.nip05 (name)
    WHERE enabled = TRUE;

CREATE INDEX IF NOT EXISTS idx_nip05_identities_public_key
    ON public.nip05_identities (public_key);

CREATE INDEX IF NOT EXISTS idx_nip05_identities_name
    ON public.nip05_identities (name);

CREATE INDEX IF NOT EXISTS idx_profiles_name
    ON public.profiles (name);

CREATE INDEX IF NOT EXISTS idx_profiles_nip05
    ON public.profiles (nip05);

CREATE INDEX IF NOT EXISTS idx_profiles_display_name
    ON public.profiles (display_name);

CREATE INDEX IF NOT EXISTS idx_banned_users_user_id
    ON public.banned_users (user_id);

CREATE INDEX IF NOT EXISTS idx_banned_users_id
    ON public.banned_users (id);

CREATE INDEX IF NOT EXISTS idx_banned_users_created_at
    ON public.banned_users (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_objects_mime_type
    ON public.objects (mime_type);

CREATE INDEX IF NOT EXISTS idx_objects_blocked
    ON public.objects (blocked);

CREATE INDEX IF NOT EXISTS idx_blossom_objects_admin_review_state
    ON public.blossom_objects_admin (review_state, updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_blossom_objects_admin_extension
    ON public.blossom_objects_admin (extension);

CREATE INDEX IF NOT EXISTS idx_blossom_objects_admin_last_downloaded_at
    ON public.blossom_objects_admin (last_downloaded_at);

CREATE INDEX IF NOT EXISTS idx_blossom_plans_scope
    ON public.blossom_plans (scope, is_default, updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_blossom_review_reports_object_hash
    ON public.blossom_review_reports (object_hash, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_blossom_review_reports_status
    ON public.blossom_review_reports (status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_blossom_review_reports_event_id
    ON public.blossom_review_reports (event_id);

CREATE INDEX IF NOT EXISTS idx_blossom_audit_log_created_at
    ON public.blossom_audit_log (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_blossom_audit_log_action
    ON public.blossom_audit_log (action, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_roles_name
    ON public.nip29_roles (name);

CREATE INDEX IF NOT EXISTS idx_groups_name
    ON public.nip29_groups (name);

CREATE INDEX IF NOT EXISTS idx_groups_last_metadata_update
    ON public.nip29_groups (last_metadata_update);

CREATE INDEX IF NOT EXISTS idx_groups_last_members_update
    ON public.nip29_groups (last_members_update);

CREATE INDEX IF NOT EXISTS idx_group_members_user_id
    ON public.nip29_group_members (user_id);

CREATE INDEX IF NOT EXISTS idx_group_members_lookup
    ON public.nip29_group_members (relay, group_id, user_id)
    WHERE banned = FALSE;

CREATE INDEX IF NOT EXISTS idx_group_bans_user_lookup
    ON public.nip29_group_bans (relay, group_id, user_id);

CREATE INDEX IF NOT EXISTS idx_group_invites_expires_at
    ON public.nip29_group_invites (expires_at);

CREATE INDEX IF NOT EXISTS idx_nip86_allowed_pubkeys_updated_at
    ON public.nip86_allowed_pubkeys (updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_nip86_banned_events_updated_at
    ON public.nip86_banned_events (updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_nip86_blocked_ips_updated_at
    ON public.nip86_blocked_ips (updated_at DESC);

-- ============================================================
-- Índices avançados
-- Rode estes FORA de uma transaction block.
-- ============================================================

-- Índices antigos de covering podem exceder o limite de tamanho por
-- tupla de índice do PostgreSQL (~2712 bytes) — problema real com
-- eventos de até ~2000 tags. GIN não sofre dessa limitação, por isso
-- toda a indexação de tags/tagvalues abaixo usa GIN.
DROP INDEX CONCURRENTLY IF EXISTS idx_event_covering_author;
DROP INDEX CONCURRENTLY IF EXISTS idx_event_covering;
DROP INDEX CONCURRENTLY IF EXISTS arbitrarytagvalues;

-- idx_event_recent removido: dependia de um epoch hardcoded e exigiria
-- recriação manual periódica. A estratégia definida para eventos
-- antigos é movê-los para uma tabela de arquivamento (plano futuro,
-- ex.: reter no máximo os últimos 5 anos em `event`), não manter um
-- índice parcial com data fixa.

CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_event_deletions
    ON public.event (created_at DESC, id)
    WHERE deleted_by IS NOT NULL;

CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_event_pubkey_created_at
    ON public.event (pubkey, created_at DESC);

CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_event_tags_gin
    ON public.event USING gin (tags jsonb_path_ops);

-- Índice que faltava para a coluna gerada `tagvalues` (estava sem
-- suporte de índice, pagando custo de escrita sem ganho de leitura).
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_event_tagvalues_gin
    ON public.event USING gin (tagvalues array_ops);

CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_event_author_kind
    ON public.event (pubkey, kind, created_at DESC);