package metrics

import "fmt"

func GetKindName(kind int) string {
	switch kind {
	case 0:
		return "KindProfileMetadata"
	case 1:
		return "KindTextNote"
	case 2:
		return "KindRecommendServer"
	case 3:
		return "KindFollowList"
	case 4:
		return "KindEncryptedDirectMessage"
	case 5:
		return "KindDeletion"
	case 6:
		return "KindRepost"
	case 7:
		return "KindReaction"
	case 8:
		return "KindBadgeAward"
	case 9:
		return "KindSimpleGroupChatMessage"
	case 10:
		return "KindSimpleGroupThreadedReply"
	case 11:
		return "KindSimpleGroupThread"
	case 12:
		return "KindSimpleGroupReply"
	case 13:
		return "KindSeal"
	case 14:
		return "KindDirectMessage"
	case 16:
		return "KindGenericRepost"
	case 17:
		return "KindReactionToWebsite"
	case 40:
		return "KindChannelCreation"
	case 41:
		return "KindChannelMetadata"
	case 42:
		return "KindChannelMessage"
	case 43:
		return "KindChannelHideMessage"
	case 44:
		return "KindChannelMuteUser"
	case 64:
		return "KindChess"
	case 818:
		return "KindMergeRequests"
	case 1021:
		return "KindBid"
	case 1022:
		return "KindBidConfirmation"
	case 1040:
		return "KindOpenTimestamps"
	case 1059:
		return "KindGiftWrap"
	case 1063:
		return "KindFileMetadata"
	case 1311:
		return "KindLiveChatMessage"
	case 1617:
		return "KindPatch"
	case 1621:
		return "KindIssue"
	case 1622:
		return "KindReply"
	case 1630:
		return "KindStatusOpen"
	case 1631:
		return "KindStatusApplied"
	case 1632:
		return "KindStatusClosed"
	case 1633:
		return "KindStatusDraft"
	case 1971:
		return "KindProblemTracker"
	case 1984:
		return "KindReporting"
	case 1985:
		return "KindLabel"
	case 1986:
		return "KindRelayReviews"
	case 1987:
		return "KindAIEmbeddings"
	case 2003:
		return "KindTorrent"
	case 2004:
		return "KindTorrentComment"
	case 2022:
		return "KindCoinjoinPool"
	case 4550:
		return "KindCommunityPostApproval"
	case 7000:
		return "KindJobFeedback"
	case 9000:
		return "KindSimpleGroupPutUser"
	case 9001:
		return "KindSimpleGroupRemoveUser"
	case 9002:
		return "KindSimpleGroupEditMetadata"
	case 9005:
		return "KindSimpleGroupDeleteEvent"
	case 9007:
		return "KindSimpleGroupCreateGroup"
	case 9008:
		return "KindSimpleGroupDeleteGroup"
	case 9009:
		return "KindSimpleGroupCreateInvite"
	case 9021:
		return "KindSimpleGroupJoinRequest"
	case 9022:
		return "KindSimpleGroupLeaveRequest"
	case 9041:
		return "KindZapGoal"
	case 9467:
		return "KindTidalLogin"
	case 9734:
		return "KindZapRequest"
	case 9735:
		return "KindZap"
	case 9802:
		return "KindHighlights"
	case 10000:
		return "KindMuteList"
	case 10001:
		return "KindPinList"
	case 10002:
		return "KindRelayListMetadata"
	case 10003:
		return "KindBookmarkList"
	case 10004:
		return "KindCommunityList"
	case 10005:
		return "KindPublicChatList"
	case 10006:
		return "KindBlockedRelayList"
	case 10007:
		return "KindSearchRelayList"
	case 10009:
		return "KindSimpleGroupList"
	case 10015:
		return "KindInterestList"
	case 10030:
		return "KindEmojiList"
	case 10050:
		return "KindDMRelayList"
	case 10063:
		return "KindUserServerList"
	case 10096:
		return "KindFileStorageServerList"
	case 10101:
		return "KindGoodWikiAuthorList"
	case 10102:
		return "KindGoodWikiRelayList"
	case 13194:
		return "KindNWCWalletInfo"
	case 21000:
		return "KindLightningPubRPC"
	case 22242:
		return "KindClientAuthentication"
	case 23194:
		return "KindNWCWalletRequest"
	case 23195:
		return "KindNWCWalletResponse"
	case 24133:
		return "KindNostrConnect"
	case 24242:
		return "KindBlobs"
	case 27235:
		return "KindHTTPAuth"
	case 30000:
		return "KindCategorizedPeopleList"
	case 30001:
		return "KindCategorizedBookmarksList"
	case 30002:
		return "KindRelaySets"
	case 30003:
		return "KindBookmarkSets"
	case 30004:
		return "KindCuratedSets"
	case 30005:
		return "KindCuratedVideoSets"
	case 30007:
		return "KindMuteSets"
	case 30008:
		return "KindProfileBadges"
	case 30009:
		return "KindBadgeDefinition"
	case 30015:
		return "KindInterestSets"
	case 30017:
		return "KindStallDefinition"
	case 30018:
		return "KindProductDefinition"
	case 30019:
		return "KindMarketplaceUI"
	case 30020:
		return "KindProductSoldAsAuction"
	case 30023:
		return "KindArticle"
	case 30024:
		return "KindDraftArticle"
	case 30030:
		return "KindEmojiSets"
	case 30040:
		return "KindModularArticleHeader"
	case 30041:
		return "KindModularArticleContent"
	case 30063:
		return "KindReleaseArtifactSets"
	case 30078:
		return "KindApplicationSpecificData"
	case 30311:
		return "KindLiveEvent"
	case 30315:
		return "KindUserStatuses"
	case 30402:
		return "KindClassifiedListing"
	case 30403:
		return "KindDraftClassifiedListing"
	case 30617:
		return "KindRepositoryAnnouncement"
	case 30618:
		return "KindRepositoryState"
	case 39000:
		return "KindSimpleGroupMetadata"
	case 39001:
		return "KindSimpleGroupAdmins"
	case 39002:
		return "KindSimpleGroupMembers"
	case 39003:
		return "KindSimpleGroupRoles"
	case 30818:
		return "KindWikiArticle"
	case 30819:
		return "KindRedirects"
	case 31890:
		return "KindFeed"
	case 31922:
		return "KindDateCalendarEvent"
	case 31923:
		return "KindTimeCalendarEvent"
	case 31924:
		return "KindCalendar"
	case 31925:
		return "KindCalendarEventRSVP"
	case 31989:
		return "KindHandlerRecommendation"
	case 31990:
		return "KindHandlerInformation"
	case 34235:
		return "KindVideoEvent"
	case 34236:
		return "KindShortVideoEvent"
	case 34237:
		return "KindVideoViewEvent"
	case 34550:
		return "KindCommunityDefinition"

	default:
		return fmt.Sprintf("Unknown Kind %d", kind)
	}
}
