// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"strings"
)

type AdminAsyncJob struct {
	Status  string   `json:"status"`
	JobID   *string  `json:"jobId,omitempty"`
	Remote  *string  `json:"remote,omitempty"`
	Relays  []string `json:"relays"`
	Message *string  `json:"message,omitempty"`
}

type AdminBanStatus struct {
	Pubkey     string   `json:"pubkey"`
	Banned     bool     `json:"banned"`
	Reason     *string  `json:"reason,omitempty"`
	RelatedIds []string `json:"relatedIds"`
	CreatedAt  *string  `json:"createdAt,omitempty"`
}

type AdminBanUserInput struct {
	Reason     *string  `json:"reason,omitempty"`
	RelatedIds []string `json:"relatedIds,omitempty"`
}

type AdminBlossomAuditPage struct {
	PageInfo *PageInfo        `json:"pageInfo"`
	Items    []map[string]any `json:"items"`
}

type AdminBlossomBulkReviewInput struct {
	Hashes []string            `json:"hashes"`
	Action BlossomReviewAction `json:"action"`
	Reason *string             `json:"reason,omitempty"`
}

type AdminBlossomMirrorInput struct {
	SourceURL      string `json:"sourceURL"`
	ExpectedSha256 string `json:"expectedSHA256"`
}

type AdminBlossomObject struct {
	Hash           string      `json:"hash"`
	UploaderPubkey string      `json:"uploaderPubkey"`
	MimeType       string      `json:"mimeType"`
	Extension      string      `json:"extension"`
	Size           int         `json:"size"`
	CreatedAt      string      `json:"createdAt"`
	ReviewState    string      `json:"reviewState"`
	ExifStatus     string      `json:"exifStatus"`
	GpsDetected    bool        `json:"gpsDetected"`
	DirectURL      string      `json:"directURL"`
	OptimizedURL   *string     `json:"optimizedURL,omitempty"`
	ThumbnailURL   *string     `json:"thumbnailURL,omitempty"`
	BlossomID      *string     `json:"blossomID,omitempty"`
	Width          *int32      `json:"width,omitempty"`
	Height         *int32      `json:"height,omitempty"`
	DurationMs     *int        `json:"durationMS,omitempty"`
	BitrateKbps    *int32      `json:"bitrateKbps,omitempty"`
	DownloadCount  int         `json:"downloadCount"`
	IngressBytes   int         `json:"ingressBytes"`
	EgressBytes    int         `json:"egressBytes"`
	FlagReason     *string     `json:"flagReason,omitempty"`
	Mirrors        []string    `json:"mirrors"`
	ReportCount    int         `json:"reportCount"`
	Nip94Tags      []*NostrTag `json:"nip94Tags"`
}

type AdminBlossomObjectFilterInput struct {
	Sha256        *string `json:"sha256,omitempty"`
	MimeType      *string `json:"mimeType,omitempty"`
	Extension     *string `json:"extension,omitempty"`
	ReviewState   *string `json:"reviewState,omitempty"`
	Pubkey        *string `json:"pubkey,omitempty"`
	UploaderQuery *string `json:"uploaderQuery,omitempty"`
}

type AdminBlossomObjectPage struct {
	PageInfo *PageInfo             `json:"pageInfo"`
	Items    []*AdminBlossomObject `json:"items"`
}

type AdminBlossomOverview struct {
	Storage map[string]any      `json:"storage"`
	Objects map[string]any      `json:"objects"`
	Traffic map[string]any      `json:"traffic"`
	Users   map[string]any      `json:"users"`
	Workers map[string]any      `json:"workers"`
	Policy  *AdminBlossomPolicy `json:"policy"`
	Alerts  []map[string]any    `json:"alerts"`
}

type AdminBlossomPlan struct {
	ID                string           `json:"id"`
	Name              string           `json:"name"`
	Scope             BlossomPlanScope `json:"scope"`
	StorageQuotaBytes *int             `json:"storageQuotaBytes,omitempty"`
	EgressQuotaBytes  *int             `json:"egressQuotaBytes,omitempty"`
	Description       *string          `json:"description,omitempty"`
	IsDefault         bool             `json:"isDefault"`
	UpdatedAt         *string          `json:"updatedAt,omitempty"`
}

type AdminBlossomPlanAssignment struct {
	PlanID      string  `json:"planId"`
	Pubkey      string  `json:"pubkey"`
	DisplayName *string `json:"displayName,omitempty"`
	Picture     *string `json:"picture,omitempty"`
	Npub        *string `json:"npub,omitempty"`
	AssignedBy  string  `json:"assignedBy"`
	AssignedAt  string  `json:"assignedAt"`
}

type AdminBlossomPlanAssignmentPage struct {
	PageInfo *PageInfo                     `json:"pageInfo"`
	Items    []*AdminBlossomPlanAssignment `json:"items"`
}

type AdminBlossomPlanInput struct {
	ID                string           `json:"id"`
	Name              string           `json:"name"`
	Scope             BlossomPlanScope `json:"scope"`
	StorageQuotaBytes *int             `json:"storageQuotaBytes,omitempty"`
	EgressQuotaBytes  *int             `json:"egressQuotaBytes,omitempty"`
	Description       *string          `json:"description,omitempty"`
	IsDefault         bool             `json:"isDefault"`
}

type AdminBlossomPolicy struct {
	Mode                                string  `json:"mode"`
	DefaultStorageQuotaBytes            *int    `json:"defaultStorageQuotaBytes,omitempty"`
	EnabledUserDefaultStorageQuotaBytes *int    `json:"enabledUserDefaultStorageQuotaBytes,omitempty"`
	DefaultEgressQuotaBytes             *int    `json:"defaultEgressQuotaBytes,omitempty"`
	EnabledUserDefaultEgressQuotaBytes  *int    `json:"enabledUserDefaultEgressQuotaBytes,omitempty"`
	UpdatedAt                           *string `json:"updatedAt,omitempty"`
}

type AdminBlossomPolicyInput struct {
	Mode string `json:"mode"`
}

type AdminBlossomReport struct {
	ID             string              `json:"id"`
	EventID        string              `json:"eventID"`
	ObjectHash     string              `json:"objectHash"`
	ReporterPubkey string              `json:"reporterPubkey"`
	ReporterNpub   *string             `json:"reporterNpub,omitempty"`
	TargetEventID  *string             `json:"targetEventID,omitempty"`
	TargetPubkey   *string             `json:"targetPubkey,omitempty"`
	ReportType     *string             `json:"reportType,omitempty"`
	Reason         *string             `json:"reason,omitempty"`
	Status         BlossomReportStatus `json:"status"`
	ResolvedBy     *string             `json:"resolvedBy,omitempty"`
	ResolvedNote   *string             `json:"resolvedNote,omitempty"`
	CreatedAt      *string             `json:"createdAt,omitempty"`
	ResolvedAt     *string             `json:"resolvedAt,omitempty"`
}

type AdminBlossomReportFilterInput struct {
	Q          *string              `json:"q,omitempty"`
	ReportType *string              `json:"reportType,omitempty"`
	Status     *BlossomReportStatus `json:"status,omitempty"`
	ObjectHash *string              `json:"objectHash,omitempty"`
}

type AdminBlossomReportPage struct {
	PageInfo *PageInfo             `json:"pageInfo"`
	Items    []*AdminBlossomReport `json:"items"`
}

type AdminBlossomResolveReportInput struct {
	Status BlossomReportStatus `json:"status"`
	Note   *string             `json:"note,omitempty"`
}

type AdminBlossomUser struct {
	Pubkey             string  `json:"pubkey"`
	DisplayName        *string `json:"displayName,omitempty"`
	Picture            *string `json:"picture,omitempty"`
	Npub               *string `json:"npub,omitempty"`
	ObjectCount        int     `json:"objectCount"`
	StorageUsedBytes   int     `json:"storageUsedBytes"`
	StorageQuotaBytes  *int    `json:"storageQuotaBytes,omitempty"`
	MonthlyEgressBytes int     `json:"monthlyEgressBytes"`
	EgressQuotaBytes   *int    `json:"egressQuotaBytes,omitempty"`
	Enabled            bool    `json:"enabled"`
	LastUploadAt       *string `json:"lastUploadAt,omitempty"`
	Notes              *string `json:"notes,omitempty"`
}

type AdminBlossomUserDetail struct {
	User  *AdminBlossomUser     `json:"user"`
	Files []*AdminBlossomObject `json:"files"`
}

type AdminBlossomUserFilterInput struct {
	Q       *string        `json:"q,omitempty"`
	SortBy  *string        `json:"sortBy,omitempty"`
	SortDir *SortDirection `json:"sortDir,omitempty"`
}

type AdminBlossomUserPage struct {
	PageInfo *PageInfo           `json:"pageInfo"`
	Items    []*AdminBlossomUser `json:"items"`
}

type AdminBlossomWhitelistInput struct {
	Pubkey            string  `json:"pubkey"`
	Enabled           bool    `json:"enabled"`
	StorageQuotaBytes *int    `json:"storageQuotaBytes,omitempty"`
	EgressQuotaBytes  *int    `json:"egressQuotaBytes,omitempty"`
	Notes             *string `json:"notes,omitempty"`
}

type AdminBlossomWorkerPage struct {
	PageInfo *PageInfo        `json:"pageInfo"`
	Items    []map[string]any `json:"items"`
}

type AdminConnection struct {
	Wsid              string  `json:"wsid"`
	IP                string  `json:"ip"`
	Authed            *string `json:"authed,omitempty"`
	SubscriptionCount int32   `json:"subscriptionCount"`
	ConnectedAt       *string `json:"connectedAt,omitempty"`
	LastSeenAt        *string `json:"lastSeenAt,omitempty"`
	UserAgent         *string `json:"userAgent,omitempty"`
}

type AdminConnectionPage struct {
	PageInfo *PageInfo          `json:"pageInfo"`
	Items    []*AdminConnection `json:"items"`
}

type AdminCreateLabelInput struct {
	Namespace string                 `json:"namespace"`
	Labels    []string               `json:"labels"`
	Comment   *string                `json:"comment,omitempty"`
	Target    *AdminLabelTargetInput `json:"target"`
}

type AdminCreateLabelPayload struct {
	Event  *NostrEvent `json:"event"`
	Stored bool        `json:"stored"`
}

type AdminDeleteJobsHistoryInput struct {
	JobName  string   `json:"jobName"`
	Statuses []string `json:"statuses,omitempty"`
}

type AdminDownloadEventsInput struct {
	Relays         []string       `json:"relays"`
	PublicKey      *string        `json:"publicKey,omitempty"`
	Kinds          []int32        `json:"kinds,omitempty"`
	Filter         map[string]any `json:"filter,omitempty"`
	TimeoutSeconds *int32         `json:"timeoutSeconds,omitempty"`
}

type AdminEventAggregates struct {
	Total      int            `json:"total"`
	Kinds      []*KindCount   `json:"kinds"`
	TopAuthors []*PubkeyCount `json:"topAuthors"`
	TopTags    []*TagCount    `json:"topTags"`
	Trends     map[string]any `json:"trends"`
}

type AdminEventDetail struct {
	Event       *NostrEvent    `json:"event"`
	Identifiers map[string]any `json:"identifiers"`
	Author      map[string]any `json:"author"`
	Hashtags    []string       `json:"hashtags"`
	ImageUrls   []string       `json:"imageUrls"`
}

type AdminEventPage struct {
	PageInfo *PageInfo     `json:"pageInfo"`
	Items    []*NostrEvent `json:"items"`
}

type AdminEventReport struct {
	ReportEventID       string  `json:"reportEventId"`
	ReporterPubkey      string  `json:"reporterPubkey"`
	ReporterNpub        *string `json:"reporterNpub,omitempty"`
	ReporterDisplayName string  `json:"reporterDisplayName"`
	ReporterPicture     *string `json:"reporterPicture,omitempty"`
	ReportedEventID     *string `json:"reportedEventId,omitempty"`
	ReportedPubkey      *string `json:"reportedPubkey,omitempty"`
	ReportType          *string `json:"reportType,omitempty"`
	Content             *string `json:"content,omitempty"`
	CreatedAt           int     `json:"createdAt"`
}

type AdminEventReportPage struct {
	PageInfo *PageInfo           `json:"pageInfo"`
	Items    []*AdminEventReport `json:"items"`
}

type AdminEventSearchInput struct {
	Q       *string                `json:"q,omitempty"`
	Authors []string               `json:"authors,omitempty"`
	Kinds   []int32                `json:"kinds,omitempty"`
	Tags    []*AdminTagFilterInput `json:"tags,omitempty"`
	Since   *int                   `json:"since,omitempty"`
	Until   *int                   `json:"until,omitempty"`
}

type AdminFetchEventInput struct {
	Relays []string `json:"relays,omitempty"`
}

type AdminFetchEventPayload struct {
	EventID      *string                  `json:"eventId,omitempty"`
	SourceRelay  *string                  `json:"sourceRelay,omitempty"`
	Found        bool                     `json:"found"`
	Persisted    bool                     `json:"persisted"`
	RelaysTried  int32                    `json:"relaysTried"`
	RelayResults []*AdminFetchRelayResult `json:"relayResults"`
	Message      *string                  `json:"message,omitempty"`
}

type AdminFetchRelayResult struct {
	Relay  string  `json:"relay"`
	Status string  `json:"status"`
	Error  *string `json:"error,omitempty"`
}

type AdminGroup struct {
	GroupID     string `json:"groupId"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Private     bool   `json:"private"`
	Closed      bool   `json:"closed"`
	Hidden      bool   `json:"hidden"`
	MemberCount int32  `json:"memberCount"`
}

type AdminImportEventsPayload struct {
	Files []*AdminImportFileResult `json:"files"`
}

type AdminImportFileResult struct {
	Filename   string  `json:"filename"`
	Total      int32   `json:"total"`
	Inserted   int32   `json:"inserted"`
	Duplicates int32   `json:"duplicates"`
	Invalid    int32   `json:"invalid"`
	Error      *string `json:"error,omitempty"`
}

type AdminJob struct {
	ID          string         `json:"id"`
	Queue       string         `json:"queue"`
	Priority    string         `json:"priority"`
	JobName     string         `json:"jobName"`
	Status      string         `json:"status"`
	Attempts    int32          `json:"attempts"`
	MaxAttempts int32          `json:"maxAttempts"`
	CreatedAt   string         `json:"createdAt"`
	StartedAt   *string        `json:"startedAt,omitempty"`
	FinishedAt  *string        `json:"finishedAt,omitempty"`
	RunAt       *string        `json:"runAt,omitempty"`
	LastError   *string        `json:"lastError,omitempty"`
	Payload     map[string]any `json:"payload,omitempty"`
	Result      map[string]any `json:"result,omitempty"`
}

type AdminJobFilterInput struct {
	Queue    *string  `json:"queue,omitempty"`
	JobName  *string  `json:"jobName,omitempty"`
	Statuses []string `json:"statuses,omitempty"`
}

type AdminJobPage struct {
	PageInfo *PageInfo   `json:"pageInfo"`
	Items    []*AdminJob `json:"items"`
}

type AdminLabelEvent struct {
	ID         string            `json:"id"`
	Pubkey     string            `json:"pubkey"`
	AuthorNpub *string           `json:"authorNpub,omitempty"`
	CreatedAt  int               `json:"createdAt"`
	Kind       int32             `json:"kind"`
	Content    string            `json:"content"`
	Namespace  string            `json:"namespace"`
	Labels     []string          `json:"labels"`
	Target     *AdminLabelTarget `json:"target"`
	Tags       []*NostrTag       `json:"tags"`
}

type AdminLabelFilterInput struct {
	Namespace  *string          `json:"namespace,omitempty"`
	Labels     []string         `json:"labels,omitempty"`
	TargetType *LabelTargetType `json:"targetType,omitempty"`
	Target     *string          `json:"target,omitempty"`
	Author     *string          `json:"author,omitempty"`
	Q          *string          `json:"q,omitempty"`
}

type AdminLabelPage struct {
	PageInfo *PageInfo          `json:"pageInfo"`
	Items    []*AdminLabelEvent `json:"items"`
}

type AdminLabelTarget struct {
	Type      LabelTargetType `json:"type"`
	Value     string          `json:"value"`
	RelayHint *string         `json:"relayHint,omitempty"`
}

type AdminLabelTargetInput struct {
	Type      LabelTargetType `json:"type"`
	Value     string          `json:"value"`
	RelayHint *string         `json:"relayHint,omitempty"`
}

type AdminLabelsSummary struct {
	TotalEvents  int          `json:"totalEvents"`
	TotalTargets int          `json:"totalTargets"`
	Namespaces   []*NameCount `json:"namespaces"`
	Labels       []*NameCount `json:"labels"`
	TargetTypes  []*NameCount `json:"targetTypes"`
}

type AdminLoggedUser struct {
	Profile         *AdminProfile `json:"profile"`
	ConnectionCount int32         `json:"connectionCount"`
	LastSeenAt      *string       `json:"lastSeenAt,omitempty"`
	ConnectionState string        `json:"connectionState"`
}

type AdminLoggedUserPage struct {
	PageInfo *PageInfo          `json:"pageInfo"`
	Items    []*AdminLoggedUser `json:"items"`
}

type AdminNegentropySyncInput struct {
	Remote         string         `json:"remote"`
	Direction      *string        `json:"direction,omitempty"`
	Filter         map[string]any `json:"filter,omitempty"`
	TimeoutSeconds *int32         `json:"timeoutSeconds,omitempty"`
}

type AdminNip05Identity struct {
	Name        string   `json:"name"`
	Pubkey      string   `json:"pubkey"`
	Npub        *string  `json:"npub,omitempty"`
	DisplayName *string  `json:"displayName,omitempty"`
	Picture     *string  `json:"picture,omitempty"`
	RelayHints  []string `json:"relayHints"`
	CreatedAt   *string  `json:"createdAt,omitempty"`
	UpdatedAt   *string  `json:"updatedAt,omitempty"`
}

type AdminNip05IdentityPage struct {
	PageInfo *PageInfo             `json:"pageInfo"`
	Items    []*AdminNip05Identity `json:"items"`
}

type AdminNip05Lookup struct {
	Pubkey   string              `json:"pubkey"`
	Exists   bool                `json:"exists"`
	Identity *AdminNip05Identity `json:"identity,omitempty"`
}

type AdminNip05UpsertInput struct {
	Name   string `json:"name"`
	Pubkey string `json:"pubkey"`
}

type AdminNip86EventPage struct {
	PageInfo *PageInfo                `json:"pageInfo"`
	Items    []*AdminNip86EventRecord `json:"items"`
}

type AdminNip86EventRecord struct {
	EventID   string  `json:"eventId"`
	Reason    *string `json:"reason,omitempty"`
	CreatedAt *string `json:"createdAt,omitempty"`
	UpdatedAt *string `json:"updatedAt,omitempty"`
	CreatedBy *string `json:"createdBy,omitempty"`
}

type AdminNip86IPPage struct {
	PageInfo *PageInfo             `json:"pageInfo"`
	Items    []*AdminNip86IPRecord `json:"items"`
}

type AdminNip86IPRecord struct {
	IP        string  `json:"ip"`
	Reason    *string `json:"reason,omitempty"`
	CreatedAt *string `json:"createdAt,omitempty"`
	UpdatedAt *string `json:"updatedAt,omitempty"`
	CreatedBy *string `json:"createdBy,omitempty"`
}

type AdminNip86PubkeyPage struct {
	PageInfo *PageInfo                 `json:"pageInfo"`
	Items    []*AdminNip86PubkeyRecord `json:"items"`
}

type AdminNip86PubkeyRecord struct {
	Pubkey    string  `json:"pubkey"`
	Reason    *string `json:"reason,omitempty"`
	CreatedAt *string `json:"createdAt,omitempty"`
	UpdatedAt *string `json:"updatedAt,omitempty"`
	CreatedBy *string `json:"createdBy,omitempty"`
}

type AdminNip86ReasonInput struct {
	Reason *string `json:"reason,omitempty"`
}

type AdminNip86RelayMetadata struct {
	RelayURL    string `json:"relayUrl"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type AdminNip86RelayMetadataInput struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

type AdminOverview struct {
	ActiveConnections int32  `json:"activeConnections"`
	AuthedConnections int32  `json:"authedConnections"`
	LoggedUsers       int32  `json:"loggedUsers"`
	BannedUsers       int32  `json:"bannedUsers"`
	IndexedEvents     int    `json:"indexedEvents"`
	EventsPerMinute   int    `json:"eventsPerMinute"`
	RelayStatus       string `json:"relayStatus"`
}

type AdminProfile struct {
	Pubkey      string   `json:"pubkey"`
	Npub        *string  `json:"npub,omitempty"`
	DisplayName string   `json:"displayName"`
	Handle      *string  `json:"handle,omitempty"`
	Picture     *string  `json:"picture,omitempty"`
	Nip05       *string  `json:"nip05,omitempty"`
	About       *string  `json:"about,omitempty"`
	Website     *string  `json:"website,omitempty"`
	Bot         bool     `json:"bot"`
	Status      *string  `json:"status,omitempty"`
	Reason      *string  `json:"reason,omitempty"`
	RelatedIds  []string `json:"relatedIds"`
	CreatedAt   *string  `json:"createdAt,omitempty"`
}

type AdminProfilePage struct {
	PageInfo *PageInfo       `json:"pageInfo"`
	Items    []*AdminProfile `json:"items"`
}

type AdminReportedEvent struct {
	TargetEventID      string         `json:"targetEventId"`
	TargetPubkey       *string        `json:"targetPubkey,omitempty"`
	TargetNevent       *string        `json:"targetNevent,omitempty"`
	TargetCreatedAt    *int           `json:"targetCreatedAt,omitempty"`
	TargetCreatedAtIso *string        `json:"targetCreatedAtIso,omitempty"`
	TargetAuthor       map[string]any `json:"targetAuthor"`
	ReportCount        int            `json:"reportCount"`
	LastReported       int            `json:"lastReported"`
	LastReportedAt     *string        `json:"lastReportedAt,omitempty"`
	ReportTypes        []string       `json:"reportTypes"`
	TargetEvent        *NostrEvent    `json:"targetEvent,omitempty"`
}

type AdminReportedEventFilterInput struct {
	Q     *string  `json:"q,omitempty"`
	Types []string `json:"types,omitempty"`
}

type AdminReportedEventPage struct {
	PageInfo *PageInfo             `json:"pageInfo"`
	Items    []*AdminReportedEvent `json:"items"`
}

type AdminReportedEventsSummary struct {
	TotalEvents         int            `json:"totalEvents"`
	TotalReports        int            `json:"totalReports"`
	UniqueTargetAuthors int            `json:"uniqueTargetAuthors"`
	Timeline            []*NameCount   `json:"timeline"`
	ReportTypes         []*NameCount   `json:"reportTypes"`
	TopAuthors          []*PubkeyCount `json:"topAuthors"`
	TopTargets          []*TargetCount `json:"topTargets"`
}

type AdminStreamStatus struct {
	Config     map[string]any `json:"config"`
	Dispatcher map[string]any `json:"dispatcher"`
	Pool       map[string]any `json:"pool"`
	Counters   map[string]any `json:"counters"`
}

type AdminTagFilterInput struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

type AdminTimeline struct {
	Bucket TimelineBucket        `json:"bucket"`
	Points []*AdminTimelinePoint `json:"points"`
}

type AdminTimelinePoint struct {
	Ts    int `json:"ts"`
	Count int `json:"count"`
}

type AdminWoTSummary struct {
	TotalNodes     int32    `json:"totalNodes"`
	TotalEdges     int32    `json:"totalEdges"`
	TrustedPubkeys []string `json:"trustedPubkeys"`
	LastComputedAt *string  `json:"lastComputedAt,omitempty"`
}

type KindCount struct {
	Kind  int32 `json:"kind"`
	Count int   `json:"count"`
}

type Mutation struct {
}

type MutationAck struct {
	Ok       bool    `json:"ok"`
	Message  *string `json:"message,omitempty"`
	EntityID *string `json:"entityId,omitempty"`
}

type NameCount struct {
	Name  string `json:"name"`
	Count int    `json:"count"`
}

type NostrEvent struct {
	ID        string      `json:"id"`
	Pubkey    string      `json:"pubkey"`
	CreatedAt int         `json:"createdAt"`
	Kind      int32       `json:"kind"`
	Tags      []*NostrTag `json:"tags"`
	Content   string      `json:"content"`
	Sig       string      `json:"sig"`
}

type NostrTag struct {
	Values []string `json:"values"`
}

type OffsetPageInput struct {
	Limit  *int32 `json:"limit,omitempty"`
	Offset *int32 `json:"offset,omitempty"`
}

type PageInfo struct {
	Total   int32 `json:"total"`
	Limit   int32 `json:"limit"`
	Offset  int32 `json:"offset"`
	HasMore bool  `json:"hasMore"`
}

type PubkeyCount struct {
	Pubkey      string  `json:"pubkey"`
	DisplayName *string `json:"displayName,omitempty"`
	Count       int     `json:"count"`
}

type Query struct {
}

type TagCount struct {
	Tag   string `json:"tag"`
	Count int    `json:"count"`
}

type TargetCount struct {
	TargetEventID string `json:"targetEventId"`
	Count         int    `json:"count"`
}

type BlossomPlanScope string

const (
	BlossomPlanScopeFree         BlossomPlanScope = "FREE"
	BlossomPlanScopeEnabledUsers BlossomPlanScope = "ENABLED_USERS"
)

var AllBlossomPlanScope = []BlossomPlanScope{
	BlossomPlanScopeFree,
	BlossomPlanScopeEnabledUsers,
}

func (e BlossomPlanScope) IsValid() bool {
	switch e {
	case BlossomPlanScopeFree, BlossomPlanScopeEnabledUsers:
		return true
	}
	return false
}

func (e BlossomPlanScope) String() string {
	return string(e)
}

func (e *BlossomPlanScope) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = BlossomPlanScope(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid BlossomPlanScope", str)
	}
	return nil
}

func (e BlossomPlanScope) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *BlossomPlanScope) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e BlossomPlanScope) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type BlossomReportStatus string

const (
	BlossomReportStatusOpen      BlossomReportStatus = "OPEN"
	BlossomReportStatusDismissed BlossomReportStatus = "DISMISSED"
	BlossomReportStatusActioned  BlossomReportStatus = "ACTIONED"
)

var AllBlossomReportStatus = []BlossomReportStatus{
	BlossomReportStatusOpen,
	BlossomReportStatusDismissed,
	BlossomReportStatusActioned,
}

func (e BlossomReportStatus) IsValid() bool {
	switch e {
	case BlossomReportStatusOpen, BlossomReportStatusDismissed, BlossomReportStatusActioned:
		return true
	}
	return false
}

func (e BlossomReportStatus) String() string {
	return string(e)
}

func (e *BlossomReportStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = BlossomReportStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid BlossomReportStatus", str)
	}
	return nil
}

func (e BlossomReportStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *BlossomReportStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e BlossomReportStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type BlossomReviewAction string

const (
	BlossomReviewActionApprove             BlossomReviewAction = "APPROVE"
	BlossomReviewActionHardDelete          BlossomReviewAction = "HARD_DELETE"
	BlossomReviewActionRequeueOptimization BlossomReviewAction = "REQUEUE_OPTIMIZATION"
)

var AllBlossomReviewAction = []BlossomReviewAction{
	BlossomReviewActionApprove,
	BlossomReviewActionHardDelete,
	BlossomReviewActionRequeueOptimization,
}

func (e BlossomReviewAction) IsValid() bool {
	switch e {
	case BlossomReviewActionApprove, BlossomReviewActionHardDelete, BlossomReviewActionRequeueOptimization:
		return true
	}
	return false
}

func (e BlossomReviewAction) String() string {
	return string(e)
}

func (e *BlossomReviewAction) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = BlossomReviewAction(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid BlossomReviewAction", str)
	}
	return nil
}

func (e BlossomReviewAction) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *BlossomReviewAction) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e BlossomReviewAction) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type LabelTargetType string

const (
	LabelTargetTypeEvent     LabelTargetType = "EVENT"
	LabelTargetTypePubkey    LabelTargetType = "PUBKEY"
	LabelTargetTypeAddress   LabelTargetType = "ADDRESS"
	LabelTargetTypeReference LabelTargetType = "REFERENCE"
	LabelTargetTypeTopic     LabelTargetType = "TOPIC"
)

var AllLabelTargetType = []LabelTargetType{
	LabelTargetTypeEvent,
	LabelTargetTypePubkey,
	LabelTargetTypeAddress,
	LabelTargetTypeReference,
	LabelTargetTypeTopic,
}

func (e LabelTargetType) IsValid() bool {
	switch e {
	case LabelTargetTypeEvent, LabelTargetTypePubkey, LabelTargetTypeAddress, LabelTargetTypeReference, LabelTargetTypeTopic:
		return true
	}
	return false
}

func (e LabelTargetType) String() string {
	return string(e)
}

func (e *LabelTargetType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	str = strings.ToUpper(strings.TrimSpace(str))
	*e = LabelTargetType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid LabelTargetType", str)
	}
	return nil
}

func (e LabelTargetType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *LabelTargetType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e LabelTargetType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SortDirection string

const (
	SortDirectionAsc  SortDirection = "ASC"
	SortDirectionDesc SortDirection = "DESC"
)

var AllSortDirection = []SortDirection{
	SortDirectionAsc,
	SortDirectionDesc,
}

func (e SortDirection) IsValid() bool {
	switch e {
	case SortDirectionAsc, SortDirectionDesc:
		return true
	}
	return false
}

func (e SortDirection) String() string {
	return string(e)
}

func (e *SortDirection) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SortDirection(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SortDirection", str)
	}
	return nil
}

func (e SortDirection) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SortDirection) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SortDirection) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TimelineBucket string

const (
	TimelineBucketHour TimelineBucket = "HOUR"
	TimelineBucketDay  TimelineBucket = "DAY"
)

var AllTimelineBucket = []TimelineBucket{
	TimelineBucketHour,
	TimelineBucketDay,
}

func (e TimelineBucket) IsValid() bool {
	switch e {
	case TimelineBucketHour, TimelineBucketDay:
		return true
	}
	return false
}

func (e TimelineBucket) String() string {
	return string(e)
}

func (e *TimelineBucket) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	str = strings.ToUpper(strings.TrimSpace(str))
	*e = TimelineBucket(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TimelineBucket", str)
	}
	return nil
}

func (e TimelineBucket) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TimelineBucket) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TimelineBucket) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
