import { adminApolloClient } from "@/graphql/client"
import { GraphQLApiError, blossomObjectFilterVars, blossomReportFilterVars, blossomUserFilterVars, emptyToNull, keysToSnake, normalizeBlossomObject, normalizeBlossomObjectRecord, normalizeBlossomOverview, normalizeBlossomPlan, normalizeBlossomPolicy, normalizeBlossomReport, normalizeBlossomUser, pageFromGraph } from "@/graphql/helpers"
import { AssignBlossomPlanDocument, BlossomAnalyticsDocument, BlossomAuditDocument, BlossomObjectDocument, BlossomObjectsDocument, BlossomOverviewDocument, BlossomPlanAssignmentsDocument, BlossomPlansDocument, BlossomPolicyDocument, BlossomReportsDocument, BlossomUserDocument, BlossomUsersDocument, BlossomWorkersDocument, DeleteBlossomPlanDocument, MirrorBlossomObjectDocument, PurgeBlossomUserDocument, ResolveBlossomReportDocument, ReviewBlossomObjectsDocument, UnassignBlossomPlanDocument, UpsertBlossomPlanDocument, UpsertBlossomPolicyDocument, UpsertBlossomWhitelistDocument } from "@/graphql/generated/operations"
import { blossomMockAnalytics, blossomMockAudit, blossomMockObjects, blossomMockOverview, blossomMockPlans, blossomMockPolicy, blossomMockReports, blossomMockUsers, blossomMockWorkers } from "@/mocks/blossom"
import { env } from "@/lib/env"
import type { AdminPage, BlossomAnalytics, BlossomAuditFilters, BlossomAuditRecord, BlossomBulkReviewPayload, BlossomBulkReviewResponse, BlossomMirrorPayload, BlossomMirrorResponse, BlossomObjectDetail, BlossomObjectsFilters, BlossomOverview, BlossomPlan, BlossomPlanAssignment, BlossomPlanAssignResponse, BlossomPlansResponse, BlossomPolicy, BlossomReportRecord, BlossomReportsFilters, BlossomResolveReportPayload, BlossomUserDetail, BlossomUserRecord, BlossomUsersFilters, BlossomWhitelistPayload, BlossomWorkerRecord, BlossomWorkersFilters } from "@/types/admin"

import { ApiError, type PageParams } from "./admin"

function toGraphApiError(error: unknown): never { if (error instanceof GraphQLApiError) throw new ApiError(error.message, error.status, error.details, error.requestId); throw error }
function isMockEnabled() { return env.mockOnFailure }
function shouldUseBlossomFallback(error: unknown) { if (isMockEnabled()) return true; return error instanceof ApiError && (error.status === 404 || error.status === 501 || error.status === 503) }
function fallbackPage<T>(items: T[], limit: number, offset: number): AdminPage<T> { const sliced = items.slice(offset, offset + limit); return { items: sliced, total: items.length, limit, offset, has_more: offset + sliced.length < items.length } }
function filterBlossomObjects(items: BlossomObjectDetail[], filters: BlossomObjectsFilters) { return items.filter((item) => (!filters.sha256 || item.hash === filters.sha256.trim()) && (!filters.mime_type || item.mime_type === filters.mime_type) && (!filters.extension || item.extension === filters.extension) && (!filters.review_state || item.review_state === filters.review_state) && (!filters.pubkey || item.uploader_pubkey === filters.pubkey.trim()) && (!filters.uploader_q || item.uploader_pubkey.toLowerCase().includes(filters.uploader_q.toLowerCase())) && (!filters.q || [item.hash, item.uploader_pubkey, item.mime_type, item.extension, item.review_state].join(" ").toLowerCase().includes(filters.q.toLowerCase()))) }
function filterBlossomReports(items: BlossomReportRecord[], filters: BlossomReportsFilters) { return items.filter((item) => (!filters.report_type || item.report_type === filters.report_type) && (!filters.status || item.status === filters.status) && (!filters.object_hash || item.object_hash === filters.object_hash.trim()) && (!filters.q || [item.object_hash, item.reporter_pubkey, item.target_event_id, item.target_pubkey, item.reason, item.report_type].filter(Boolean).join(" ").toLowerCase().includes(filters.q.toLowerCase()))) }
function filterBlossomUsers(items: BlossomUserDetail[], filters: BlossomUsersFilters) { if (!filters.q) return items; const needle = filters.q.toLowerCase(); return items.filter((item) => [item.pubkey, item.notes].filter(Boolean).join(" ").toLowerCase().includes(needle)) }
function filterBlossomAudit(items: BlossomAuditRecord[], filters: BlossomAuditFilters) { if (!filters.q) return items; const needle = filters.q.toLowerCase(); return items.filter((item) => [item.action, item.target_id, item.target_type, item.actor_pubkey].join(" ").toLowerCase().includes(needle)) }

export async function getBlossomOverview() { try { const result = await adminApolloClient.query({ query: BlossomOverviewDocument }); const data = result.data; if (!data) throw new ApiError("GraphQL query returned no data"); return normalizeBlossomOverview(data.blossomOverview) as BlossomOverview } catch (error) { if (!shouldUseBlossomFallback(error)) toGraphApiError(error); return blossomMockOverview } }
export async function getBlossomPolicy() { try { const result = await adminApolloClient.query({ query: BlossomPolicyDocument }); const data = result.data; if (!data) throw new ApiError("GraphQL query returned no data"); return normalizeBlossomPolicy(data.blossomPolicy) as BlossomPolicy } catch (error) { if (!shouldUseBlossomFallback(error)) toGraphApiError(error); return blossomMockPolicy } }
export async function updateBlossomPolicy(payload: BlossomPolicy) { try { const result = await adminApolloClient.mutate({ mutation: UpsertBlossomPolicyDocument, variables: { input: { mode: payload.mode } } }); const data = result.data; if (!data) throw new ApiError("GraphQL mutation returned no data"); return normalizeBlossomPolicy(data.upsertBlossomPolicy) as BlossomPolicy } catch (error) { if (!shouldUseBlossomFallback(error)) toGraphApiError(error); return payload } }
export async function getBlossomPlans(scope?: string) { try { const result = await adminApolloClient.query({ query: BlossomPlansDocument }); const data = result.data; if (!data) throw new ApiError("GraphQL query returned no data"); const items = data.blossomPlans.map(normalizeBlossomPlan); return { items: scope ? items.filter((item: any) => item.scope === scope) : items } as BlossomPlansResponse } catch (error) { if (!shouldUseBlossomFallback(error)) toGraphApiError(error); return { items: scope ? blossomMockPlans.filter((item) => item.scope === scope) : blossomMockPlans } } }
export async function upsertBlossomPlan(payload: BlossomPlan) { try { const result = await adminApolloClient.mutate({ mutation: UpsertBlossomPlanDocument, variables: { input: { id: payload.id, name: payload.name, scope: String(payload.scope ?? "").toUpperCase(), storageQuotaBytes: payload.storage_quota_bytes ?? null, egressQuotaBytes: payload.egress_quota_bytes ?? null, description: payload.description ?? null, isDefault: payload.is_default } } as any }); const data = result.data; if (!data) throw new ApiError("GraphQL mutation returned no data"); return normalizeBlossomPlan(data.upsertBlossomPlan) as BlossomPlan } catch (error) { if (!shouldUseBlossomFallback(error)) toGraphApiError(error); return payload } }
export async function deleteBlossomPlan(id: string) { try { await adminApolloClient.mutate({ mutation: DeleteBlossomPlanDocument, variables: { id } }); return { ok: true, id } } catch (error) { if (!shouldUseBlossomFallback(error)) toGraphApiError(error); return { ok: true, id } } }
export async function assignBlossomPlan(payload: { plan_id: string; pubkey: string }) { try { await adminApolloClient.mutate({ mutation: AssignBlossomPlanDocument, variables: { planId: payload.plan_id, pubkey: payload.pubkey } }); return { ok: true, plan_id: payload.plan_id, pubkey: payload.pubkey } as BlossomPlanAssignResponse } catch (error) { if (!shouldUseBlossomFallback(error)) toGraphApiError(error); return { ok: true, plan_id: payload.plan_id, pubkey: payload.pubkey } } }
export async function unassignBlossomPlan(payload: { plan_id: string; pubkey: string }) { try { await adminApolloClient.mutate({ mutation: UnassignBlossomPlanDocument, variables: { planId: payload.plan_id, pubkey: payload.pubkey } }); return { ok: true, plan_id: payload.plan_id, pubkey: payload.pubkey } } catch (error) { if (!shouldUseBlossomFallback(error)) toGraphApiError(error); return { ok: true, plan_id: payload.plan_id, pubkey: payload.pubkey } } }
export async function getBlossomPlanAssignments(planId: string) { try { const result = await adminApolloClient.query({ query: BlossomPlanAssignmentsDocument, variables: { planId } }); const data = result.data; if (!data) throw new ApiError("GraphQL query returned no data"); return { items: data.blossomPlanAssignments.items.map((item: any) => keysToSnake(item)) as BlossomPlanAssignment[] } } catch (error) { toGraphApiError(error) } }
export async function getBlossomObjects(filters: BlossomObjectsFilters, params: PageParams) { try { const result = await adminApolloClient.query({ query: BlossomObjectsDocument, variables: { filter: blossomObjectFilterVars(new URLSearchParams(buildSearch({ ...filters }))), page: { limit: params.limit, offset: params.offset } } }); const data = result.data; if (!data) throw new ApiError("GraphQL query returned no data"); return pageFromGraph(data.blossomObjects, normalizeBlossomObject) as AdminPage<BlossomObjectDetail> } catch (error) { if (!shouldUseBlossomFallback(error)) toGraphApiError(error); return fallbackPage(filterBlossomObjects(blossomMockObjects, filters), params.limit, params.offset) } }
export async function getBlossomObjectDetail(hash: string) { try { const result = await adminApolloClient.query({ query: BlossomObjectDocument, variables: { hash } }); const data = result.data; if (!data) throw new ApiError("GraphQL query returned no data"); return normalizeBlossomObject(data.blossomObject) as BlossomObjectDetail } catch (error) { if (!shouldUseBlossomFallback(error)) toGraphApiError(error); const item = blossomMockObjects.find((entry) => entry.hash === hash); if (!item) throw error; return item } }
export async function reviewBlossomObjects(payload: BlossomBulkReviewPayload) { try { await adminApolloClient.mutate({ mutation: ReviewBlossomObjectsDocument, variables: { input: { hashes: payload.hashes ?? [], action: String(payload.action ?? "").toUpperCase(), reason: payload.reason ?? null } } as any }); return { ok: true, updated: payload.hashes.length } as BlossomBulkReviewResponse } catch (error) { if (!shouldUseBlossomFallback(error)) toGraphApiError(error); return { ok: true, updated: payload.hashes.length } } }
export async function getBlossomUsers(filters: BlossomUsersFilters, params: PageParams) { try { const result = await adminApolloClient.query({ query: BlossomUsersDocument, variables: { filter: blossomUserFilterVars(new URLSearchParams(buildSearch(filters))) as any, page: { limit: params.limit, offset: params.offset } } }); const data = result.data; if (!data) throw new ApiError("GraphQL query returned no data"); return pageFromGraph(data.blossomUsers, normalizeBlossomUser) as AdminPage<BlossomUserRecord> } catch (error) { if (!shouldUseBlossomFallback(error)) toGraphApiError(error); return fallbackPage(filterBlossomUsers(blossomMockUsers, filters), params.limit, params.offset) } }
export async function getBlossomUserDetail(pubkey: string) { try { const result = await adminApolloClient.query({ query: BlossomUserDocument, variables: { pubkey } }); const data = result.data; if (!data) throw new ApiError("GraphQL query returned no data"); return { ...normalizeBlossomUser(data.blossomUser.user), files: data.blossomUser.files.map(normalizeBlossomObjectRecord) } as BlossomUserDetail } catch (error) { if (!shouldUseBlossomFallback(error)) toGraphApiError(error); const item = blossomMockUsers.find((entry) => entry.pubkey === pubkey); if (!item) throw error; return item } }
export async function upsertBlossomWhitelistEntry(payload: BlossomWhitelistPayload) { try { const result = await adminApolloClient.mutate({ mutation: UpsertBlossomWhitelistDocument, variables: { input: { pubkey: payload.pubkey, enabled: payload.enabled, storageQuotaBytes: payload.storage_quota_bytes ?? null, egressQuotaBytes: payload.egress_quota_bytes ?? null, notes: payload.notes ?? null } } }); const data = result.data; if (!data) throw new ApiError("GraphQL mutation returned no data"); return normalizeBlossomUser(data.upsertBlossomWhitelist) as BlossomWhitelistPayload } catch (error) { if (!shouldUseBlossomFallback(error)) toGraphApiError(error); return payload } }
export async function purgeBlossomUser(pubkey: string) { try { await adminApolloClient.mutate({ mutation: PurgeBlossomUserDocument, variables: { pubkey } }); return { ok: true, pubkey } } catch (error) { if (!shouldUseBlossomFallback(error)) toGraphApiError(error); return { ok: true, pubkey } } }
export async function createBlossomMirrorJob(payload: BlossomMirrorPayload) { try { const result = await adminApolloClient.mutate({ mutation: MirrorBlossomObjectDocument, variables: { input: { sourceURL: payload.source_url, expectedSHA256: payload.expected_sha256 } } }); const data = result.data; if (!data) throw new ApiError("GraphQL mutation returned no data"); return { ok: true, job_id: data.mirrorBlossomObject.jobId, status: data.mirrorBlossomObject.status } as BlossomMirrorResponse } catch (error) { if (!shouldUseBlossomFallback(error)) toGraphApiError(error); return { ok: true, job_id: "mirror-mock-001", status: "queued" } } }
export async function getBlossomWorkers(filters: BlossomWorkersFilters = {}) { try { const result = await adminApolloClient.query({ query: BlossomWorkersDocument, variables: { status: emptyToNull(filters.status ?? null), jobType: emptyToNull(filters.job_type ?? null), targetHash: emptyToNull(filters.target_hash ?? null) } }); const data = result.data; if (!data) throw new ApiError("GraphQL query returned no data"); return (data.blossomWorkers.items ?? []).map((item: any) => keysToSnake(item)) as BlossomWorkerRecord[] } catch (error) { if (!shouldUseBlossomFallback(error)) toGraphApiError(error); return blossomMockWorkers.filter((item) => (!filters.status || item.status === filters.status) && (!filters.job_type || item.job_type === filters.job_type) && (!filters.target_hash || item.target_hash === filters.target_hash)) } }
export async function getBlossomReports(filters: BlossomReportsFilters, params: PageParams) { try { const result = await adminApolloClient.query({ query: BlossomReportsDocument, variables: { filter: blossomReportFilterVars(new URLSearchParams(buildSearch(filters))) as any, page: { limit: params.limit, offset: params.offset } } }); const data = result.data; if (!data) throw new ApiError("GraphQL query returned no data"); return pageFromGraph(data.blossomReports, normalizeBlossomReport) as AdminPage<BlossomReportRecord> } catch (error) { if (!shouldUseBlossomFallback(error)) toGraphApiError(error); return fallbackPage(filterBlossomReports(blossomMockReports, filters), params.limit, params.offset) } }
export async function resolveBlossomReport(payload: BlossomResolveReportPayload) { try { const result = await adminApolloClient.mutate({ mutation: ResolveBlossomReportDocument, variables: { id: payload.id, input: { status: String(payload.status ?? "").toUpperCase(), note: payload.note ?? null } } as any }); const data = result.data; if (!data) throw new ApiError("GraphQL mutation returned no data"); return { ok: true, id: data.resolveBlossomReport.id, status: String(data.resolveBlossomReport.status).toLowerCase() } } catch (error) { if (!shouldUseBlossomFallback(error)) toGraphApiError(error); return { ok: true, id: payload.id, status: payload.status } } }
export async function getBlossomAnalytics() { try { const result = await adminApolloClient.query({ query: BlossomAnalyticsDocument }); const data = result.data; if (!data) throw new ApiError("GraphQL query returned no data"); return keysToSnake(data.blossomAnalytics) as BlossomAnalytics } catch (error) { if (!shouldUseBlossomFallback(error)) toGraphApiError(error); return blossomMockAnalytics } }
export async function getBlossomAudit(filters: BlossomAuditFilters, params: PageParams) { try { const result = await adminApolloClient.query({ query: BlossomAuditDocument, variables: { page: { limit: params.limit, offset: params.offset } } }); const data = result.data; if (!data) throw new ApiError("GraphQL query returned no data"); return pageFromGraph(data.blossomAudit, (item: any) => keysToSnake(item)) as AdminPage<BlossomAuditRecord> } catch (error) { if (!shouldUseBlossomFallback(error)) toGraphApiError(error); return fallbackPage(filterBlossomAudit(blossomMockAudit, filters), params.limit, params.offset) } }

function buildSearch(search: Record<string, string | number | undefined>) { const params = new URLSearchParams(); for (const [key, value] of Object.entries(search)) { if (value !== undefined && value !== "") params.set(key, String(value)) } return params.toString() }
