import { adminApolloClient } from "@/graphql/client"
import { GraphQLApiError, keysToSnake, pageFromGraph } from "@/graphql/helpers"
import { CreateNip86AllowedPubkeyDocument, CreateNip86BannedEventDocument, CreateNip86BlockedIpDocument, DeleteNip05Document, DeleteNip86AllowedPubkeyDocument, DeleteNip86BannedEventDocument, DeleteNip86BlockedIpDocument, Nip05IdentitiesDocument, Nip86AllowedPubkeysDocument, Nip86BannedEventsDocument, Nip86BlockedIpsDocument, Nip86RelayMetadataDocument, UpdateNip86RelayMetadataDocument, UpsertNip05Document, UserNip05Document } from "@/graphql/generated/operations"
import type { AdminPage, NIP05Identity, NIP05IdentityPayload, NIP86EventRecord, NIP86IPRecord, NIP86PubKeyRecord, NIP86ReasonPayload, NIP86RelayMetadata, NIP86RelayMetadataPayload, UserNIP05Association } from "@/types/admin"

import { ApiError, type PageParams } from "./admin"

function toGraphApiError(error: unknown): never { if (error instanceof GraphQLApiError) throw new ApiError(error.message, error.status, error.details, error.requestId); throw error }

export async function getNIP05Page(query: string, params: PageParams) {
  try { const result = await adminApolloClient.query({ query: Nip05IdentitiesDocument, variables: { q: query || null, page: { limit: params.limit, offset: params.offset } } }); const data = result.data; if (!data) throw new ApiError("GraphQL query returned no data"); return pageFromGraph(data.nip05Identities, (item: any) => keysToSnake(item)) as AdminPage<NIP05Identity> } catch (error) { toGraphApiError(error) }
}
export async function upsertNIP05Identity(payload: NIP05IdentityPayload) { try { const result = await adminApolloClient.mutate({ mutation: UpsertNip05Document, variables: { input: payload } }); const data = result.data; if (!data) throw new ApiError("GraphQL mutation returned no data"); return keysToSnake(data.upsertNip05) as NIP05Identity } catch (error) { toGraphApiError(error) } }
export async function deleteNIP05Identity(name: string) { try { await adminApolloClient.mutate({ mutation: DeleteNip05Document, variables: { name } }); return { name, deleted: true } } catch (error) { toGraphApiError(error) } }
export async function getUserNIP05(pubkey: string) { try { const result = await adminApolloClient.query({ query: UserNip05Document, variables: { pubkey } }); const data = result.data; if (!data) throw new ApiError("GraphQL query returned no data"); return { pubkey: data.userNip05.pubkey, exists: data.userNip05.exists, name: data.userNip05.identity?.name ?? undefined, display_name: data.userNip05.identity?.displayName ?? undefined, picture: data.userNip05.identity?.picture ?? undefined, relay_hints: data.userNip05.identity?.relayHints, created_at: data.userNip05.identity?.createdAt ?? undefined, updated_at: data.userNip05.identity?.updatedAt ?? undefined } satisfies UserNIP05Association } catch (error) { toGraphApiError(error) } }
export async function getNIP86AllowedPubKeysPage(query: string, params: PageParams) { try { const result = await adminApolloClient.query({ query: Nip86AllowedPubkeysDocument, variables: { q: query || null, page: { limit: params.limit, offset: params.offset } } }); const data = result.data; if (!data) throw new ApiError("GraphQL query returned no data"); return pageFromGraph(data.nip86AllowedPubkeys, (item: any) => keysToSnake(item)) as AdminPage<NIP86PubKeyRecord> } catch (error) { toGraphApiError(error) } }
export async function allowNIP86PubKey(pubkey: string, payload: NIP86ReasonPayload) { try { await adminApolloClient.mutate({ mutation: CreateNip86AllowedPubkeyDocument, variables: { pubkey, input: { reason: payload.reason ?? null } } }); return { ok: true } } catch (error) { toGraphApiError(error) } }
export async function unallowNIP86PubKey(pubkey: string) { try { await adminApolloClient.mutate({ mutation: DeleteNip86AllowedPubkeyDocument, variables: { pubkey } }); return { ok: true } } catch (error) { toGraphApiError(error) } }
export async function getNIP86BlockedIPsPage(query: string, params: PageParams) { try { const result = await adminApolloClient.query({ query: Nip86BlockedIpsDocument, variables: { q: query || null, page: { limit: params.limit, offset: params.offset } } }); const data = result.data; if (!data) throw new ApiError("GraphQL query returned no data"); return pageFromGraph(data.nip86BlockedIps, (item: any) => keysToSnake(item)) as AdminPage<NIP86IPRecord> } catch (error) { toGraphApiError(error) } }
export async function blockNIP86IP(ip: string, payload: NIP86ReasonPayload) { try { await adminApolloClient.mutate({ mutation: CreateNip86BlockedIpDocument, variables: { ip, input: { reason: payload.reason ?? null } } }); return { ok: true } } catch (error) { toGraphApiError(error) } }
export async function unblockNIP86IP(ip: string) { try { await adminApolloClient.mutate({ mutation: DeleteNip86BlockedIpDocument, variables: { ip } }); return { ok: true } } catch (error) { toGraphApiError(error) } }
export async function getNIP86BannedEventsPage(query: string, params: PageParams) { try { const result = await adminApolloClient.query({ query: Nip86BannedEventsDocument, variables: { q: query || null, page: { limit: params.limit, offset: params.offset } } }); const data = result.data; if (!data) throw new ApiError("GraphQL query returned no data"); return pageFromGraph(data.nip86BannedEvents, (item: any) => keysToSnake(item)) as AdminPage<NIP86EventRecord> } catch (error) { toGraphApiError(error) } }
export async function banNIP86Event(eventID: string, payload: NIP86ReasonPayload) { try { await adminApolloClient.mutate({ mutation: CreateNip86BannedEventDocument, variables: { eventId: eventID, input: { reason: payload.reason ?? null } } }); return { ok: true } } catch (error) { toGraphApiError(error) } }
export async function unbanNIP86Event(eventID: string) { try { await adminApolloClient.mutate({ mutation: DeleteNip86BannedEventDocument, variables: { eventId: eventID } }); return { ok: true } } catch (error) { toGraphApiError(error) } }
export async function getNIP86RelayMetadata() { try { const result = await adminApolloClient.query({ query: Nip86RelayMetadataDocument }); const data = result.data; if (!data) throw new ApiError("GraphQL query returned no data"); return keysToSnake(data.nip86RelayMetadata) as NIP86RelayMetadata } catch (error) { toGraphApiError(error) } }
export async function updateNIP86RelayMetadata(payload: NIP86RelayMetadataPayload) { try { const result = await adminApolloClient.mutate({ mutation: UpdateNip86RelayMetadataDocument, variables: { input: payload } }); const data = result.data; if (!data) throw new ApiError("GraphQL mutation returned no data"); return { updated: true, ...keysToSnake(data.updateNip86RelayMetadata) } } catch (error) { toGraphApiError(error) } }
