import { adminApolloClient } from "@/graphql/client"
import { GraphQLApiError, extractDeletedCount, keysToSnake, listToPage, mapDownloadJob, pageFromGraph } from "@/graphql/helpers"
import { AddTrustedPubkeyDocument, CancelJobDocument, DeleteJobsHistoryDocument, DownloadEventsDocument, DownloadJobDocument, DownloadJobsDocument, GroupsDocument, JobDocument, JobsDocument, RemoveTrustedPubkeyDocument, ResumeJobDocument, RetryJobDocument, StartNegentropySyncDocument, WotSummaryDocument } from "@/graphql/generated/operations"
import type { AdminGroupResponse, AdminJobsFilters, AdminJobsResponse, AdminJob, AdminJobStatus, AdminWoTSummaryResponse, DownloadEventsRequest, DownloadJob, DownloadJobsResponse, NegentropySyncRequest, NegentropySyncResponse } from "@/types/admin"

import { ApiError, type PageParams } from "./admin"

function toGraphApiError(error: unknown): never { if (error instanceof GraphQLApiError) throw new ApiError(error.message, error.status, error.details, error.requestId); throw error }

export async function startNegentropySync(payload: NegentropySyncRequest) { try { const result = await adminApolloClient.mutate({ mutation: StartNegentropySyncDocument, variables: { input: { remote: payload.remote, direction: payload.direction, filter: (payload.filter ?? null) as any, timeoutSeconds: payload.timeout ?? null } } as any }); const data = result.data; if (!data) throw new ApiError("GraphQL mutation returned no data"); return { status: data.startNegentropySync.status, remote: data.startNegentropySync.remote ?? "", message: data.startNegentropySync.message ?? "", job_id: data.startNegentropySync.jobId ?? undefined } as NegentropySyncResponse } catch (error) { toGraphApiError(error) } }
export async function startDownloadEvents(payload: DownloadEventsRequest) { try { const result = await adminApolloClient.mutate({ mutation: DownloadEventsDocument, variables: { input: { relays: payload.relays ?? [], publicKey: payload.public_key ?? null, kinds: payload.kinds ?? null, filter: payload.filter ?? null, timeoutSeconds: payload.timeout ?? null } } }); const data = result.data; if (!data) throw new ApiError("GraphQL mutation returned no data"); return { status: data.downloadEvents.status, job_id: data.downloadEvents.jobId ?? undefined, relays: data.downloadEvents.relays, message: data.downloadEvents.message ?? "" } as any } catch (error) { toGraphApiError(error) } }
export async function getDownloadJobs() { try { const result = await adminApolloClient.query({ query: DownloadJobsDocument }); const data = result.data; if (!data) throw new ApiError("GraphQL query returned no data"); return { items: data.jobs.items.map((item: any) => mapDownloadJob(item) as DownloadJob) } as DownloadJobsResponse } catch (error) { toGraphApiError(error) } }
export async function getDownloadJob(jobID: string) { try { const result = await adminApolloClient.query({ query: DownloadJobDocument, variables: { id: jobID } }); const data = result.data; if (!data) throw new ApiError("GraphQL query returned no data"); return mapDownloadJob(data.job) as DownloadJob } catch (error) { toGraphApiError(error) } }
function toJobsFilter(filters: AdminJobsFilters = {}) { return { queue: filters.queue ?? null, jobName: filters.job_name ?? null, statuses: filters.statuses ?? [] } }
export async function getJobs(filters: AdminJobsFilters = {}) { try { const result = await adminApolloClient.query({ query: JobsDocument, variables: { filter: toJobsFilter(filters), page: undefined } }); const data = result.data; if (!data) throw new ApiError("GraphQL query returned no data"); return pageFromGraph(data.jobs, (item: any) => keysToSnake(item)) as AdminJobsResponse } catch (error) { toGraphApiError(error) } }
export async function getJob(jobID: string, queue?: string) { try { const result = await adminApolloClient.query({ query: JobDocument, variables: { id: jobID, queue: queue ?? null } }); const data = result.data; if (!data) throw new ApiError("GraphQL query returned no data"); return keysToSnake(data.job) as AdminJob } catch (error) { toGraphApiError(error) } }
export async function retryJob(jobID: string, queue: string) { try { await adminApolloClient.mutate({ mutation: RetryJobDocument, variables: { id: jobID, queue } }); return { ok: true, id: jobID, queue } } catch (error) { toGraphApiError(error) } }
export async function resumeJob(jobID: string, queue: string) { try { await adminApolloClient.mutate({ mutation: ResumeJobDocument, variables: { id: jobID, queue } }); return { ok: true, id: jobID, queue } } catch (error) { toGraphApiError(error) } }
export async function cancelJob(jobID: string, queue: string) { try { await adminApolloClient.mutate({ mutation: CancelJobDocument, variables: { id: jobID, queue } }); return { ok: true, id: jobID, queue } } catch (error) { toGraphApiError(error) } }
export async function deleteJobsHistory(filters: { job_name: string; queue?: string; statuses?: AdminJobStatus[] }) { try { const result = await adminApolloClient.mutate({ mutation: DeleteJobsHistoryDocument, variables: { input: { jobName: filters.job_name, statuses: filters.statuses ?? [] } } }); const data = result.data; if (!data) throw new ApiError("GraphQL mutation returned no data"); return { deleted: extractDeletedCount(data.deleteJobsHistory.message) } } catch (error) { toGraphApiError(error) } }
export async function getGroupsPage(params: PageParams) { try { const result = await adminApolloClient.query({ query: GroupsDocument }); const data = result.data; if (!data) throw new ApiError("GraphQL query returned no data"); return listToPage(data.groups.map((item: any) => keysToSnake(item)), new URLSearchParams({ limit: String(params.limit), offset: String(params.offset) })) as unknown as { items: AdminGroupResponse[]; total: number; limit: number; offset: number; has_more: boolean } } catch (error) { toGraphApiError(error) } }
export async function getWoTSummary() { try { const result = await adminApolloClient.query({ query: WotSummaryDocument }); const data = result.data; if (!data) throw new ApiError("GraphQL query returned no data"); return keysToSnake(data.wotSummary) as AdminWoTSummaryResponse } catch (error) { toGraphApiError(error) } }
export async function addTrustedPubkey(pubkey: string) { try { await adminApolloClient.mutate({ mutation: AddTrustedPubkeyDocument, variables: { pubkey } }); return { pubkey, added: true } } catch (error) { toGraphApiError(error) } }
export async function removeTrustedPubkey(pubkey: string) { try { await adminApolloClient.mutate({ mutation: RemoveTrustedPubkeyDocument, variables: { pubkey } }); return { pubkey, removed: true } } catch (error) { toGraphApiError(error) } }
